import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";

export const metadata: Metadata = { title: "About MEMORIES", description: "MEMORIES is a Saudi-born travel platform for dream journeys, visits to Saudi Arabia and study-abroad planning." };

export default function AboutPage() {
  return <main className="innerPage"><section className="pageHero container"><p className="kicker">What we are</p><h1>One dream.<br /><em>One complete journey.</em></h1><p>MEMORIES is a Saudi-born travel platform designed to turn an idea into a coordinated journey. We bring destinations, dates, flights, stays, private drivers, experiences and practical support into one thoughtful plan.</p></section><section className="container storyGrid"><article><span>01</span><h2>Dream journeys</h2><p>Personal holidays for families, couples, friends and explorers—built around the country, cities, dates, pace and total budget that work for them.</p></article><article><span>02</span><h2>Discover Saudi Arabia</h2><p>Welcoming journeys for visitors coming to experience the Kingdom’s cities, heritage, landscapes, culture and sacred destinations.</p></article><article><span>03</span><h2>Study abroad</h2><p>A clearer route for students planning an overseas education, including destination guidance and assistance with travel, accommodation and visa applications.</p></article></section><section className="container aboutStatement"><p className="kicker light">Saudi roots. Global outlook.</p><h2>We begin by understanding the person, not selling a package.</h2><p>Every request gives us the context needed to shape the next step: where you want to go, why you are travelling, who is joining you, when you will travel and what the complete journey should cost. From there, MEMORIES can prepare a plan that feels personal, practical and possible.</p><Link className="button gold" href="/design-your-journey">Design your dream journey <ArrowRight size={16} /></Link></section></main>;
}
