import { travelCountries } from "./components/planner-data";

export type Locale = "en" | "ar";

export type CityGuide = {
  slug: string;
  nameEn: string;
  nameAr: string;
  image: string;
  introEn: string;
  introAr: string;
  placesEn: string[];
  placesAr: string[];
  days: string;
};

export type CountryGuide = {
  slug: string;
  nameEn: string;
  nameAr: string;
  // Search-only words, carried over from the planner's country list so the
  // catalogue and the planner find a country by the same names. Türkiye is
  // the reason: nobody types the U.
  aliases?: string;
  image: string;
  region: string;
  regionAr: string;
  taglineEn: string;
  taglineAr: string;
  introEn: string;
  introAr: string;
  cuisineEn: string[];
  cuisineAr: string[];
  experiencesEn: string[];
  experiencesAr: string[];
  cities: CityGuide[];
};

type Profile = Omit<CountryGuide, "slug" | "nameEn" | "nameAr" | "cities">;
type CityDetail = Pick<CityGuide, "introEn" | "introAr" | "placesEn" | "placesAr" | "days">;

const profiles: Record<string, Profile> = {
  "saudi-arabia": { image: "/images/alula.webp", region: "Arabian Peninsula", regionAr: "شبه الجزيرة العربية", taglineEn: "Living heritage, generous tables and extraordinary landscapes.", taglineAr: "تراث حي وموائد كريمة وطبيعة استثنائية.", introEn: "Move from future-facing cities to ancient desert stories, cool mountains and the Red Sea, with every stop shaped around the way you like to travel.", introAr: "انتقل من المدن التي تصنع المستقبل إلى حكايات الصحراء القديمة والجبال الباردة والبحر الأحمر، في مسار مصمم حول طريقتك في السفر.", cuisineEn: ["Najdi and Hijazi classics", "Saudi coffee and dates", "Regional seafood and contemporary Saudi dining"], cuisineAr: ["أطباق نجدية وحجازية", "القهوة السعودية والتمور", "مأكولات بحرية ومطبخ سعودي معاصر"], experiencesEn: ["Heritage with a local storyteller", "Desert, mountain or coastal time", "A dining route shaped around regional flavours"], experiencesAr: ["تراث بصحبة راوٍ محلي", "وقت في الصحراء أو الجبال أو الساحل", "مسار طعام حول النكهات المحلية"] },
  france: { image: "/images/paris.webp", region: "Europe", regionAr: "أوروبا", taglineEn: "Art, beautiful tables and cities made for lingering.", taglineAr: "فن وموائد جميلة ومدن تدعوك للتمهل.", introEn: "Choose grand boulevards, Mediterranean light, vineyard country or storybook towns, then let us connect the right pace and places.", introAr: "اختر الشوارع الكبرى أو ضوء المتوسط أو مزارع العنب أو البلدات الحالمة، وسنربط لك الأماكن بالإيقاع المناسب.", cuisineEn: ["Seasonal bistro cooking", "Pâtisserie and artisan bread", "Regional cheese, seafood and market produce"], cuisineAr: ["أطباق البسترو الموسمية", "المعجنات والخبز الحرفي", "الأجبان والمأكولات البحرية ومنتجات الأسواق"], experiencesEn: ["A neighbourhood food walk", "Art and architecture at an unhurried pace", "A scenic day beyond the city"], experiencesAr: ["جولة طعام بين الأحياء", "الفن والعمارة بإيقاع مريح", "يوم جميل خارج المدينة"] },
  italy: { image: "/images/destinations/italy.png", region: "Europe", regionAr: "أوروبا", taglineEn: "Art, ritual and unforgettable regional cooking.", taglineAr: "فن وتقاليد ومطابخ محلية لا تُنسى.", introEn: "Build a journey around ancient cities, Renaissance beauty, lake views or the coast, with room for long lunches and spontaneous discoveries.", introAr: "ابنِ رحلتك حول المدن القديمة وجمال عصر النهضة والبحيرات أو الساحل، مع وقت للموائد الطويلة والاكتشافات العفوية.", cuisineEn: ["Regional pasta and risotto", "Local markets and espresso bars", "Gelato, seafood and countryside produce"], cuisineAr: ["الباستا والريزوتو المحلي", "الأسواق ومقاهي الإسبريسو", "الجيلاتو والمأكولات البحرية ومنتجات الريف"], experiencesEn: ["An early-access cultural visit", "A cooking or market experience", "A beautiful rail or road connection"], experiencesAr: ["زيارة ثقافية في وقت هادئ", "تجربة طبخ أو سوق محلي", "رحلة قطار أو طريق بمناظر جميلة"] },
  spain: { image: "/images/destinations/spain.png", region: "Europe", regionAr: "أوروبا", taglineEn: "Expressive cities, late dinners and Mediterranean rhythm.", taglineAr: "مدن نابضة وعشاء متأخر وإيقاع متوسطي.", introEn: "Combine art-filled capitals, Andalusian history and restorative coastal time in a journey with energy and warmth.", introAr: "اجمع بين عواصم الفن وتاريخ الأندلس ووقت مريح على الساحل في رحلة مليئة بالحيوية والدفء.", cuisineEn: ["Tapas and market produce", "Paella and coastal seafood", "Regional sweets and café culture"], cuisineAr: ["التاباس ومنتجات الأسواق", "الباييلا ومأكولات الساحل", "الحلويات المحلية وثقافة المقاهي"], experiencesEn: ["An evening tapas route", "Architecture and old-quarter walks", "A beach, vineyard or village day"], experiencesAr: ["مسار تاباس مسائي", "جولات العمارة والأحياء القديمة", "يوم على الشاطئ أو في قرية أو مزرعة عنب"] },
  switzerland: { image: "/images/switzerland.webp", region: "Europe", regionAr: "أوروبا", taglineEn: "Lakes, alpine air and journeys that feel effortless.", taglineAr: "بحيرات وهواء جبلي ورحلات تسير بسلاسة.", introEn: "Pair polished cities with mountain railways, lakeside stays and quiet villages, all connected by one of Europe’s easiest transport networks.", introAr: "اجمع بين المدن الأنيقة وقطارات الجبال والإقامة على البحيرات والقرى الهادئة، عبر شبكة تنقل من الأسهل في أوروبا.", cuisineEn: ["Fondue and raclette", "Alpine bakeries and chocolate", "Seasonal lake and mountain cooking"], cuisineAr: ["الفوندو والراكليت", "مخابز الألب والشوكولاتة", "أطباق البحيرات والجبال الموسمية"], experiencesEn: ["A panoramic rail journey", "A lake cruise or mountain viewpoint", "A slow day in an alpine village"], experiencesAr: ["رحلة قطار بانورامية", "جولة بحيرة أو إطلالة جبلية", "يوم هادئ في قرية ألبية"] },
  turkey: { image: "/images/istanbul.webp", region: "Europe & Asia", regionAr: "أوروبا وآسيا", taglineEn: "Layered history, generous flavours and dramatic coasts.", taglineAr: "تاريخ متراكم ونكهات سخية وسواحل مهيبة.", introEn: "Travel between storied cities, surreal landscapes and clear-water coasts with hospitality at the centre of every day.", introAr: "تنقل بين المدن التاريخية والطبيعة السريالية والسواحل الصافية، مع ضيافة حاضرة في كل يوم.", cuisineEn: ["Meze, grills and regional breakfasts", "Baklava and Turkish coffee", "Aegean seafood and market produce"], cuisineAr: ["المقبلات والمشاوي والفطور التركي", "البقلاوة والقهوة التركية", "مأكولات بحر إيجة ومنتجات الأسواق"], experiencesEn: ["A market and food discovery", "A private cruise or scenic drive", "History brought to life with a guide"], experiencesAr: ["اكتشاف الأسواق والطعام", "جولة بحرية خاصة أو طريق جميل", "تاريخ ينبض بالحياة مع مرشد"] },
  maldives: { image: "/images/maldives.webp", region: "Indian Ocean", regionAr: "المحيط الهندي", taglineEn: "Private calm, luminous water and time that finally slows.", taglineAr: "هدوء خاص ومياه مضيئة ووقت يتباطأ أخيرًا.", introEn: "Choose the atoll and resort style that suit your privacy, family, diving and budget preferences, rather than choosing from photographs alone.", introAr: "اختر الجزيرة والمنتجع الأنسب للخصوصية والعائلة والغوص والميزانية، بدل الاختيار من الصور وحدها.", cuisineEn: ["Fresh reef fish and coconut", "Resort dining experiences", "Maldivian breakfasts and tropical fruit"], cuisineAr: ["أسماك طازجة وجوز الهند", "تجارب مطاعم المنتجعات", "فطور مالديفي وفاكهة استوائية"], experiencesEn: ["Snorkelling or diving", "A private sandbank afternoon", "Spa, sunset and unhurried family time"], experiencesAr: ["السنوركل أو الغوص", "ظهيرة خاصة على جزيرة رملية", "سبا وغروب ووقت عائلي هادئ"] },
  "united-kingdom": { image: "/images/destinations/london.png", region: "Europe", regionAr: "أوروبا", taglineEn: "Iconic cities, green escapes and stories around every corner.", taglineAr: "مدن أيقونية وطبيعة خضراء وحكايات عند كل زاوية.", introEn: "Shape your time around theatre, football, museums, universities, countryside and characterful neighbourhoods.", introAr: "صمّم وقتك حول المسرح وكرة القدم والمتاحف والجامعات والريف والأحياء المميزة.", cuisineEn: ["Modern British dining", "Afternoon tea and bakeries", "Global neighbourhood restaurants"], cuisineAr: ["المطبخ البريطاني الحديث", "شاي بعد الظهر والمخابز", "مطاعم عالمية في الأحياء"] , experiencesEn: ["A theatre or match evening", "Museums chosen around your interests", "A countryside or university-town day"], experiencesAr: ["أمسية مسرح أو مباراة", "متاحف حسب اهتماماتك", "يوم في الريف أو مدينة جامعية"] },
  "united-states": { image: "/images/destinations/united-states.png", region: "North America", regionAr: "أمريكا الشمالية", taglineEn: "Big-city energy and landscapes on an unforgettable scale.", taglineAr: "طاقة المدن وطبيعة بمقياس لا يُنسى.", introEn: "Build a focused city stay, family theme-park escape, coastal road trip or national-park adventure without trying to do everything at once.", introAr: "صمّم إقامة مركزة في مدينة أو رحلة عائلية للمنتزهات أو طريقًا ساحليًا أو مغامرة طبيعية، من دون محاولة فعل كل شيء دفعة واحدة.", cuisineEn: ["Neighbourhood food scenes", "Regional barbecue and seafood", "Creative dining from cultures around the world"], cuisineAr: ["مطاعم الأحياء", "الشواء والمأكولات البحرية المحلية", "مطابخ مبتكرة من ثقافات العالم"] , experiencesEn: ["A skyline or waterfront day", "Live sport, music or theatre", "A memorable day trip beyond the city"], experiencesAr: ["يوم بين الأفق العمراني والواجهة البحرية", "رياضة أو موسيقى أو مسرح حي", "رحلة يومية خارج المدينة"] },
  japan: { image: "/images/destinations/japan.png", region: "Asia", regionAr: "آسيا", taglineEn: "Quiet traditions, thrilling cities and thoughtful hospitality.", taglineAr: "تقاليد هادئة ومدن مبهرة وضيافة متقنة.", introEn: "Connect energetic cities, temple towns, seasonal landscapes and deeply considered stays with smooth rail travel.", introAr: "اربط المدن الحيوية وبلدات المعابد والطبيعة الموسمية والإقامات المتقنة عبر قطارات سلسة.", cuisineEn: ["Sushi, ramen and izakaya dining", "Regional specialities and markets", "Tea, wagashi and meticulous cafés"], cuisineAr: ["السوشي والرامن ومطاعم الإيزاكايا", "الأطباق المحلية والأسواق", "الشاي والحلويات والمقاهي المتقنة"] , experiencesEn: ["A food district after dark", "Temples, gardens and craft traditions", "A seamless rail day between cities"], experiencesAr: ["حي طعام بعد الغروب", "معابد وحدائق وحرف تقليدية", "يوم قطار سلس بين المدن"] },
  uae: { image: "/images/destinations/uae.png", region: "Arabian Gulf", regionAr: "الخليج العربي", taglineEn: "Bold cities, cultural landmarks and restorative desert calm.", taglineAr: "مدن جريئة ومعالم ثقافية وهدوء الصحراء.", introEn: "Balance architecture, family attractions and remarkable dining with beach, desert or mountain time.", introAr: "وازن بين العمارة والأنشطة العائلية والمطاعم الاستثنائية ووقت الشاطئ أو الصحراء أو الجبال.", cuisineEn: ["Emirati flavours", "Destination restaurants", "Levantine, Asian and global dining"], cuisineAr: ["نكهات إماراتية", "مطاعم مميزة", "مطابخ شامية وآسيوية وعالمية"] , experiencesEn: ["Architecture and cultural icons", "A desert or mountain escape", "Shopping and dining shaped around your style"], experiencesAr: ["عمارة ومعالم ثقافية", "رحلة صحراء أو جبال", "تسوق وطعام حسب ذوقك"] },
  greece: { image: "/images/destinations/greece.png", region: "Europe", regionAr: "أوروبا", taglineEn: "Ancient stories, Aegean light and island time.", taglineAr: "حكايات قديمة وضوء إيجة ووقت الجزر.", introEn: "Pair the history of Athens with the island whose pace, beaches and atmosphere best suit you.", introAr: "اجمع بين تاريخ أثينا والجزيرة التي يناسبك إيقاعها وشواطئها وأجواؤها.", cuisineEn: ["Meze and grilled seafood", "Village tavernas", "Olive oil, pastries and island produce"], cuisineAr: ["المقبلات والمأكولات البحرية المشوية", "مطاعم القرى", "زيت الزيتون والمعجنات ومنتجات الجزر"] , experiencesEn: ["An archaeological morning", "A sailing or beach day", "Sunset in a village or old harbour"], experiencesAr: ["صباح أثري", "يوم إبحار أو شاطئ", "غروب في قرية أو ميناء قديم"] },
  indonesia: { image: "/images/destinations/indonesia.png", region: "Asia", regionAr: "آسيا", taglineEn: "Tropical nature, soulful culture and restorative stays.", taglineAr: "طبيعة استوائية وثقافة عميقة وإقامات مريحة.", introEn: "Choose temples and rice terraces, urban creativity, volcanic landscapes or island waters, then set a rhythm that leaves room to breathe.", introAr: "اختر المعابد ومدرجات الأرز أو الإبداع الحضري أو البراكين أو مياه الجزر، ثم حدد إيقاعًا يمنحك مساحة للراحة.", cuisineEn: ["Nasi goreng and satay", "Regional spice and seafood", "Tropical fruit and contemporary cafés"], cuisineAr: ["ناسي غورينغ وساتاي", "بهارات محلية ومأكولات بحرية", "فاكهة استوائية ومقاهٍ معاصرة"] , experiencesEn: ["Temples and living traditions", "A nature or water day", "Wellness, craft and local food"], experiencesAr: ["معابد وتقاليد حية", "يوم في الطبيعة أو الماء", "عافية وحرف وطعام محلي"] },
  thailand: { image: "/images/destinations/thailand.png", region: "Asia", regionAr: "آسيا", taglineEn: "Warm hospitality, vivid flavours and islands for every mood.", taglineAr: "ضيافة دافئة ونكهات حيوية وجزر لكل مزاج.", introEn: "Blend Bangkok’s energy, northern culture and the beach destination that best matches your family, privacy and activity level.", introAr: "اجمع بين طاقة بانكوك وثقافة الشمال والوجهة الشاطئية الأنسب لعائلتك وخصوصيتك ومستوى نشاطك.", cuisineEn: ["Street-food classics", "Southern seafood and curries", "Northern dishes and tropical fruit"], cuisineAr: ["أطباق الشارع الشهيرة", "مأكولات الجنوب البحرية والكاري", "أطباق الشمال والفاكهة الاستوائية"] , experiencesEn: ["Markets and neighbourhood food", "Temples and cultural craft", "An island, jungle or wellness day"], experiencesAr: ["أسواق وطعام الأحياء", "معابد وحرف ثقافية", "يوم جزيرة أو غابة أو عافية"] },
  australia: { image: "/images/destinations/australia.png", region: "Oceania", regionAr: "أوقيانوسيا", taglineEn: "Harbour cities, remarkable wildlife and endless coast.", taglineAr: "مدن موانئ وحياة برية مذهلة وساحل بلا نهاية.", introEn: "Connect polished cities, beach time, wildlife and extraordinary landscapes without losing days to unnecessary travel.", introAr: "اربط المدن الأنيقة ووقت الشاطئ والحياة البرية والطبيعة الاستثنائية من دون إهدار الأيام في التنقل.", cuisineEn: ["Modern Australian dining", "Coastal seafood", "Coffee culture and multicultural neighbourhoods"], cuisineAr: ["المطبخ الأسترالي الحديث", "مأكولات الساحل البحرية", "ثقافة القهوة وأحياء متعددة الثقافات"] , experiencesEn: ["A harbour or coastal walk", "Wildlife in a responsible setting", "A scenic drive, reef or wine-country day"], experiencesAr: ["نزهة ميناء أو ساحل", "حياة برية بتجربة مسؤولة", "طريق جميل أو شعاب أو منطقة مزارع"] },
  canada: { image: "/images/destinations/canada.png", region: "North America", regionAr: "أمريكا الشمالية", taglineEn: "Welcoming cities, turquoise lakes and mountain air.", taglineAr: "مدن مرحبة وبحيرات فيروزية وهواء جبلي.", introEn: "Pair a cosmopolitan city with the scenery that brought you to Canada, from the Rockies to coastlines and historic eastern towns.", introAr: "اجمع بين مدينة عالمية والطبيعة التي جذبتك إلى كندا، من الروكي إلى السواحل وبلدات الشرق التاريخية.", cuisineEn: ["Regional comfort food", "Pacific and Atlantic seafood", "Global dining in multicultural cities"], cuisineAr: ["أطباق محلية دافئة", "مأكولات بحرية من الهادئ والأطلسي", "مطاعم عالمية في مدن متعددة الثقافات"] , experiencesEn: ["A waterfront neighbourhood day", "Mountains, lakes or forest", "Markets, museums and local sport"], experiencesAr: ["يوم في أحياء الواجهة البحرية", "جبال أو بحيرات أو غابات", "أسواق ومتاحف ورياضة محلية"] },
  austria: { image: "/images/destinations/austria.png", region: "Europe", regionAr: "أوروبا", taglineEn: "Imperial cities, alpine lakes and music in the air.", taglineAr: "مدن إمبراطورية وبحيرات ألبية وموسيقى في الأجواء.", introEn: "Combine elegant city culture with lakes, mountain villages and rail journeys that feel taken from a storybook.", introAr: "اجمع بين ثقافة المدن الأنيقة والبحيرات والقرى الجبلية ورحلات القطار التي تبدو من حكاية.", cuisineEn: ["Schnitzel and alpine dishes", "Coffee houses and pastries", "Seasonal market cooking"], cuisineAr: ["شنيتزل وأطباق ألبية", "المقاهي والمعجنات", "أطباق الأسواق الموسمية"] , experiencesEn: ["Music, palaces and architecture", "An alpine lake or mountain day", "A historic café and market route"], experiencesAr: ["موسيقى وقصور وعمارة", "يوم بحيرة أو جبل", "مسار مقاهٍ وأسواق تاريخية"] },
  portugal: { image: "/images/destinations/spain.png", region: "Europe", regionAr: "أوروبا", taglineEn: "Atlantic light, tiled streets and soulful cooking.", taglineAr: "ضوء الأطلسي وشوارع مبلطة ومطبخ بروح عميقة.", introEn: "Move between hilltop cities, river valleys, palaces and Atlantic beaches in a journey that feels relaxed and richly textured.", introAr: "تنقل بين مدن التلال ووديان الأنهار والقصور وشواطئ الأطلسي في رحلة مريحة وغنية بالتفاصيل.", cuisineEn: ["Pastéis and historic cafés", "Atlantic seafood", "Regional grills, olive oil and market produce"], cuisineAr: ["باستيل ومقاهٍ تاريخية", "مأكولات الأطلسي البحرية", "مشاوي وزيت زيتون ومنتجات الأسواق"] , experiencesEn: ["Old-quarter streets and viewpoints", "A river, coast or wine-country day", "Music, markets and neighbourhood tables"], experiencesAr: ["شوارع الأحياء القديمة والإطلالات", "يوم نهر أو ساحل أو مزارع", "موسيقى وأسواق وموائد الأحياء"] },
};

const cityDetails: Record<string, CityDetail> = {
  "saudi-arabia/riyadh": { introEn: "A confident capital where Diriyah heritage, ambitious architecture and one of the region’s fastest-moving dining scenes meet.", introAr: "عاصمة واثقة تجمع تراث الدرعية والعمارة الطموحة وأحد أسرع مشاهد المطاعم تطورًا في المنطقة.", placesEn: ["Diriyah and At-Turaif", "The National Museum and Al Murabba", "Kingdom Centre, KAFD and the city skyline"], placesAr: ["الدرعية وحي الطريف", "المتحف الوطني والمربع", "برج المملكة ومركز الملك عبدالله المالي وأفق المدينة"], days: "3–5" },
  "saudi-arabia/jeddah": { introEn: "A relaxed Red Sea city shaped by historic Al-Balad, waterfront evenings and a creative character all its own.", introAr: "مدينة هادئة على البحر الأحمر شكلتها جدة التاريخية وأمسيات الواجهة البحرية وروح إبداعية خاصة بها.", placesEn: ["Historic Jeddah, Al-Balad", "The Corniche and Jeddah Waterfront", "Red Sea islands, reefs and boat days"], placesAr: ["جدة التاريخية والبلد", "الكورنيش وواجهة جدة البحرية", "جزر وشعاب ورحلات البحر الأحمر"], days: "3–5" },
  "saudi-arabia/alula": { introEn: "Monumental sandstone landscapes, ancient stories and carefully considered experiences beneath wide desert skies.", introAr: "تكوينات رملية مهيبة وحكايات قديمة وتجارب مدروسة تحت سماء الصحراء الواسعة.", placesEn: ["Hegra archaeological site", "AlUla Old Town and the oasis", "Elephant Rock and the desert at sunset"], placesAr: ["موقع الحِجر الأثري", "بلدة العلا القديمة والواحة", "جبل الفيل والصحراء عند الغروب"], days: "3–4" },
  "saudi-arabia/makkah": { introEn: "A journey centred on worship, meaning and practical comfort, with every detail planned respectfully around your visit.", introAr: "رحلة تتمحور حول العبادة والمعنى والراحة العملية، مع تخطيط كل تفصيل باحترام حول زيارتك.", placesEn: ["Al Masjid Al Haram", "Hira Cultural District", "Museums and historic sites around Makkah"], placesAr: ["المسجد الحرام", "حي حراء الثقافي", "المتاحف والمواقع التاريخية حول مكة"], days: "3–6" },
  "saudi-arabia/madinah": { introEn: "A city of profound spiritual meaning, layered history and a calm that stays with its visitors.", introAr: "مدينة ذات معنى روحاني عميق وتاريخ متجذر وسكينة تبقى مع زوارها.", placesEn: ["Al Masjid an Nabawi", "Quba Mosque", "Uhud Mountain and historic farms"], placesAr: ["المسجد النبوي", "مسجد قباء", "جبل أحد والمزارع التاريخية"], days: "3–5" },
  "saudi-arabia/red-sea": { introEn: "Clear water, thriving reefs and private coastal stays create a restorative side of Saudi Arabia few travellers expect.", introAr: "مياه صافية وشعاب نابضة وإقامات ساحلية خاصة تكشف جانبًا مريحًا وغير متوقع من السعودية.", placesEn: ["The Red Sea’s island landscapes", "Coral reefs and protected waters", "Desert-meets-sea sunset viewpoints"], placesAr: ["مناظر جزر البحر الأحمر", "الشعاب المرجانية والمياه المحمية", "إطلالات الغروب حيث تلتقي الصحراء بالبحر"], days: "4–6" },
  "saudi-arabia/abha": { introEn: "Cool mountain air, cloud-level viewpoints, painted villages and the proud culture of Aseer.", introAr: "هواء جبلي عليل وإطلالات فوق السحاب وقرى ملونة وثقافة عسيرية أصيلة.", placesEn: ["Abha Art Street and city viewpoints", "Soudah mountain", "Rijal Almaa heritage village"], placesAr: ["شارع الفن وإطلالات أبها", "جبل السودة", "قرية رجال ألمع التراثية"], days: "3–5" },
  "saudi-arabia/aseer": { introEn: "The wider mountain region beyond Abha, hanging villages, high-altitude towns and forests few travellers ever reach.", introAr: "المنطقة الجبلية الأوسع خارج أبها، قرى معلقة وبلدات مرتفعة وغابات نادرًا ما يصلها المسافرون.", placesEn: ["Al Habala hanging village", "Al Namas highlands", "Tanomah forests and waterfalls"], placesAr: ["قرية الهبلة المعلقة", "مرتفعات النماص", "غابات وشلالات تنومة"], days: "2–4" },
  "saudi-arabia/taif": { introEn: "A breezy mountain escape known for rose farms, scenic roads and a gentler summer climate.", introAr: "ملاذ جبلي منعش يشتهر بمزارع الورد والطرق الجميلة وأجوائه الصيفية المعتدلة.", placesEn: ["Taif rose farms", "Al Hada mountain road", "Shubra Palace and seasonal markets"], placesAr: ["مزارع ورد الطائف", "طريق جبل الهدا", "قصر شبرا والأسواق الموسمية"], days: "2–4" },
  "saudi-arabia/al-ahsa": { introEn: "A vast living oasis of date palms, caves, artisan traditions and warm Eastern Province hospitality.", introAr: "واحة حية شاسعة من النخيل والكهوف والحرف التقليدية وضيافة المنطقة الشرقية.", placesEn: ["Al Ahsa Oasis", "Al Qarah Mountain", "Al Qaisariya Souq and Yellow Lake"], placesAr: ["واحة الأحساء", "جبل القارة", "سوق القيصرية وبحيرة الأصفر"], days: "2–4" },
  "saudi-arabia/jazan": { introEn: "A lush southern region of island water, green mountain terraces and distinctive local culture.", introAr: "منطقة جنوبية خصبة تجمع مياه الجزر ومدرجات الجبال الخضراء وثقافة محلية مميزة.", placesEn: ["Farasan Islands", "Jazan waterfront", "Fayfa mountain terraces"], placesAr: ["جزر فرسان", "واجهة جازان البحرية", "مدرجات جبال فيفاء"], days: "4–6" },
  "saudi-arabia/al-jouf": { introEn: "Northern heritage, olive country and archaeological landscapes reward travellers who enjoy going deeper.", introAr: "تراث شمالي وأرض الزيتون ومشاهد أثرية تكافئ من يحب التعمق في المكان.", placesEn: ["Marid Castle", "Dumat Al-Jandal old town", "Sakaka’s museums and archaeological sites"], placesAr: ["قلعة مارد", "بلدة دومة الجندل القديمة", "متاحف ومواقع سكاكا الأثرية"], days: "2–4" },
  "saudi-arabia/dammam": { introEn: "An easy-going Gulf base for waterfront time, contemporary culture and family-friendly days across the Eastern Province.", introAr: "قاعدة هادئة على الخليج للواجهات البحرية والثقافة المعاصرة والأيام العائلية في المنطقة الشرقية.", placesEn: ["Dammam and Al Khobar corniches", "Ithra in Dhahran", "Half Moon Bay and coastal escapes"], placesAr: ["كورنيش الدمام والخبر", "إثراء في الظهران", "خليج نصف القمر والوجهات الساحلية"], days: "2–4" },
  "saudi-arabia/tabuk": { introEn: "Dramatic valleys, clear coastlines and an adventurous north-western landscape rich in stories.", introAr: "أودية مهيبة وسواحل صافية وطبيعة شمالية غربية مفعمة بالمغامرة والحكايات.", placesEn: ["Wadi Al Disah", "Tabuk Castle", "Magna and the north-west coast"], placesAr: ["وادي الديسة", "قلعة تبوك", "مقنا وساحل الشمال الغربي"], days: "3–5" },
  "saudi-arabia/yanbu": { introEn: "A quieter Red Sea escape with a historic old town, clear reefs and relaxed waterfront evenings.", introAr: "وجهة أكثر هدوءًا على البحر الأحمر ببلدة تاريخية وشعاب صافية وأمسيات مريحة على الواجهة البحرية.", placesEn: ["Historic Yanbu", "Yanbu waterfront", "Coral reefs and diving sites"], placesAr: ["ينبع التاريخية", "واجهة ينبع البحرية", "الشعاب المرجانية ومواقع الغوص"], days: "3–4" },
  "france/paris": { introEn: "A city of art, neighbourhood rituals and beautiful tables, best experienced with enough space to notice the details.", introAr: "مدينة للفن وطقوس الأحياء والموائد الجميلة، والأفضل أن تعيشها بوقت يسمح لك بملاحظة التفاصيل.", placesEn: ["The Louvre and the Tuileries", "The Eiffel Tower, Trocadéro and the Seine", "Montmartre and the streets of Saint-Germain"], placesAr: ["اللوفر وحدائق التويلري", "برج إيفل وتروكاديرو ونهر السين", "مونمارتر وشوارع سان جيرمان"], days: "4–6" },
  "france/nice": { introEn: "Mediterranean colour, an elegant waterfront and a walkable old town make Nice an effortless Riviera base.", introAr: "ألوان المتوسط وواجهة بحرية أنيقة ومدينة قديمة سهلة للمشي تجعل نيس قاعدة مثالية للريفييرا.", placesEn: ["Promenade des Anglais", "Vieux Nice and Cours Saleya", "Castle Hill and the Riviera coastline"], placesAr: ["ممشى الإنجليز", "نيس القديمة وسوق كور ساليا", "تل القلعة وساحل الريفييرا"], days: "3–5" },
  "italy/rome": { introEn: "Ancient layers, expressive streets and late dinners turn every day in Rome into a story of its own.", introAr: "طبقات تاريخية وشوارع نابضة وعشاء متأخر تجعل كل يوم في روما حكاية مستقلة.", placesEn: ["The Colosseum and Roman Forum", "The Vatican Museums and St Peter’s", "Trastevere, the Pantheon and hidden piazzas"], placesAr: ["الكولوسيوم والمنتدى الروماني", "متاحف الفاتيكان وكاتدرائية القديس بطرس", "تراستيفيري والبانثيون والساحات الخفية"], days: "4–6" },
  "italy/florence": { introEn: "Renaissance masterpieces, artisan streets and Tuscan cooking come together in a remarkably intimate city.", introAr: "روائع عصر النهضة وشوارع الحرفيين ومطبخ توسكانا تجتمع في مدينة شديدة الحميمية.", placesEn: ["The Duomo and historic centre", "The Uffizi Gallery", "Oltrarno and a Tuscan countryside day"], placesAr: ["الدوومو والمركز التاريخي", "معرض أوفيزي", "أولترارنو ويوم في ريف توسكانا"], days: "3–5" },
  "spain/barcelona": { introEn: "Gaudí architecture, Mediterranean energy and neighbourhood food culture make Barcelona easy to love.", introAr: "عمارة غاودي وطاقة المتوسط وثقافة طعام الأحياء تجعل برشلونة سهلة الحب.", placesEn: ["Sagrada Família", "The Gothic Quarter and El Born", "Park Güell and the Mediterranean waterfront"], placesAr: ["ساغرادا فاميليا", "الحي القوطي وإل بورن", "حديقة غويل والواجهة المتوسطية"], days: "4–6" },
  "switzerland/interlaken": { introEn: "A lake-and-mountain base where scenic railways and unforgettable alpine days begin at the doorstep.", introAr: "قاعدة بين البحيرات والجبال تبدأ منها رحلات القطارات والمناظر الألبية مباشرة.", placesEn: ["Lake Thun and Lake Brienz", "Lauterbrunnen valley", "Jungfrau region mountain railways"], placesAr: ["بحيرتا ثون وبرينز", "وادي لاوتربرونن", "قطارات جبال منطقة يونغفراو"], days: "4–6" },
  "turkey/istanbul": { introEn: "Mosques, palaces, neighbourhood tables and the Bosphorus create a city that feels both monumental and personal.", introAr: "المساجد والقصور وموائد الأحياء والبوسفور تصنع مدينة مهيبة وشخصية في الوقت نفسه.", placesEn: ["Hagia Sophia and Sultanahmet", "Topkapı Palace and the Grand Bazaar", "The Bosphorus and waterfront neighbourhoods"], placesAr: ["آيا صوفيا والسلطان أحمد", "قصر طوب قابي والبازار الكبير", "البوسفور وأحياء الواجهة البحرية"], days: "4–6" },
  "united-kingdom/london": { introEn: "Theatre, museums, football, royal landmarks and characterful neighbourhoods make London endlessly adaptable.", introAr: "المسرح والمتاحف وكرة القدم والمعالم الملكية والأحياء المميزة تجعل لندن قابلة للتصميم لكل شخص.", placesEn: ["Westminster and the South Bank", "The British Museum and major galleries", "Notting Hill, Mayfair and neighbourhood markets"], placesAr: ["وستمنستر والضفة الجنوبية", "المتحف البريطاني والمعارض الكبرى", "نوتنغ هيل ومايفير وأسواق الأحياء"], days: "5–7" },
  "united-states/new-york": { introEn: "A city of neighbourhoods, skyline moments and world-class culture that rewards a plan built around your interests.", introAr: "مدينة أحياء وإطلالات وثقافة عالمية تكافئ الخطة المبنية حول اهتماماتك.", placesEn: ["Central Park and Museum Mile", "Lower Manhattan and the harbour", "Brooklyn neighbourhoods and the High Line"], placesAr: ["سنترال بارك وميل المتاحف", "مانهاتن السفلى والميناء", "أحياء بروكلين وهاي لاين"], days: "5–7" },
  "japan/tokyo": { introEn: "Neon energy, quiet gardens and precise everyday rituals make Tokyo feel like many cities in one.", introAr: "طاقة الأضواء وحدائق هادئة وطقوس يومية متقنة تجعل طوكيو تبدو كمدن عديدة في مدينة واحدة.", placesEn: ["Asakusa and the eastern districts", "Shibuya, Harajuku and Omotesando", "Meiji Shrine, gardens and contemporary museums"], placesAr: ["أساكوسا وأحياء الشرق", "شيبويا وهاراجوكو وأوموتيساندو", "ضريح ميجي والحدائق والمتاحف المعاصرة"], days: "5–7" },
  "uae/dubai": { introEn: "Architecture, beaches, family attractions and global dining come together in a city built for choice.", introAr: "العمارة والشواطئ والأنشطة العائلية والمطاعم العالمية تجتمع في مدينة مبنية على تنوع الخيارات.", placesEn: ["Downtown Dubai and Burj Khalifa", "Al Fahidi, the Creek and old souqs", "The coast, desert and modern districts"], placesAr: ["وسط دبي وبرج خليفة", "الفهيدي والخور والأسواق القديمة", "الساحل والصحراء والأحياء الحديثة"], days: "4–6" },
  "greece/athens": { introEn: "Ancient landmarks, energetic neighbourhoods and modern Greek dining make Athens far more than an island stopover.", introAr: "المعالم القديمة والأحياء الحيوية والمطبخ اليوناني الحديث تجعل أثينا أكثر من مجرد محطة قبل الجزر.", placesEn: ["The Acropolis and Acropolis Museum", "Plaka and Anafiotika", "The Agora, Monastiraki and the Athens Riviera"], placesAr: ["الأكروبوليس ومتحفه", "بلاكا وأنافيتوتيكا", "الأغورا وموناستيراكي وريفييرا أثينا"], days: "3–5" },
  "indonesia/bali": { introEn: "Temple rituals, rice terraces, creative coastal towns and restorative stays offer many different versions of Bali.", introAr: "طقوس المعابد ومدرجات الأرز والبلدات الساحلية الإبداعية والإقامات المريحة تقدم نسخًا عديدة من بالي.", placesEn: ["Ubud and the central highlands", "Uluwatu and the southern cliffs", "Temples, rice terraces and quieter coasts"], placesAr: ["أوبود والمرتفعات الوسطى", "أولواتو ومنحدرات الجنوب", "المعابد ومدرجات الأرز والسواحل الهادئة"], days: "6–9" },
  "thailand/bangkok": { introEn: "Temples, river life, night markets and ambitious restaurants give Bangkok an energy that never feels one-dimensional.", introAr: "المعابد وحياة النهر والأسواق الليلية والمطاعم الطموحة تمنح بانكوك طاقة متعددة الأوجه.", placesEn: ["The Grand Palace and Wat Pho", "The Chao Phraya River", "Chinatown, markets and contemporary districts"], placesAr: ["القصر الكبير ووات فو", "نهر تشاو فرايا", "الحي الصيني والأسواق والأحياء الحديثة"], days: "3–5" },
  "australia/sydney": { introEn: "A spectacular harbour, ocean walks and polished neighbourhoods make Sydney feel outdoorsy and cosmopolitan at once.", introAr: "ميناء مذهل وممرات محيطية وأحياء أنيقة تجعل سيدني طبيعية وعالمية في آن واحد.", placesEn: ["The Opera House and Circular Quay", "Bondi to Coogee coastal walk", "The Rocks, harbour beaches and nearby national parks"], placesAr: ["دار الأوبرا وسيركولار كواي", "مسار بوندي إلى كوجي الساحلي", "ذا روكس وشواطئ الميناء والحدائق الوطنية القريبة"], days: "5–7" },
  "canada/vancouver": { introEn: "Ocean, mountains and multicultural neighbourhoods meet in one of the world’s easiest cities for combining nature and urban life.", introAr: "يلتقي المحيط والجبال والأحياء متعددة الثقافات في مدينة تجمع الطبيعة والحياة الحضرية بسهولة.", placesEn: ["Stanley Park and the seawall", "Granville Island", "North Shore mountains and nearby coastal escapes"], placesAr: ["ستانلي بارك والمسار البحري", "جزيرة غرانفيل", "جبال الشاطئ الشمالي والوجهات الساحلية القريبة"], days: "4–6" },
  "austria/vienna": { introEn: "Imperial architecture, music, museums and coffee-house ritual give Vienna a composed beauty.", introAr: "العمارة الإمبراطورية والموسيقى والمتاحف وطقوس المقاهي تمنح فيينا جمالًا متزنًا.", placesEn: ["Schönbrunn Palace", "The Hofburg and museum quarter", "Historic coffee houses and the Ringstrasse"], placesAr: ["قصر شونبرون", "هوفبورغ وحي المتاحف", "المقاهي التاريخية وشارع الرينغ"], days: "3–5" },
  "portugal/lisbon": { introEn: "Hilltop viewpoints, tiled streets, river light and soulful cooking make Lisbon immediately inviting.", introAr: "إطلالات التلال والشوارع المبلطة وضوء النهر والمطبخ العميق تجعل لشبونة مرحبة منذ اللحظة الأولى.", placesEn: ["Alfama and the castle viewpoints", "Belém and the riverfront", "Chiado, Príncipe Real and a day in Sintra"], placesAr: ["ألفاما وإطلالات القلعة", "بيليم والواجهة النهرية", "شيادو وبرينسيبي ريال ويوم في سينترا"], days: "4–6" },
};

const fallbackPlaces = (cityEn: string, cityAr: string) => ({
  en: [`${cityEn}’s historic heart and signature landmarks`, `Local museums, markets and characterful neighbourhoods`, `A scenic viewpoint, waterfront or nature escape nearby`],
  ar: [`القلب التاريخي والمعالم المميزة في ${cityAr}`, `المتاحف والأسواق والأحياء ذات الطابع المحلي`, `إطلالة أو واجهة مائية أو وجهة طبيعية قريبة`],
});

// Countries the planner can already build a real trip for, but which the
// public catalogue has no photography for. A country card is a full-bleed
// photo with the name over it, so the only two ways to ship one of these
// today are a broken tile or another country's photo captioned Malaysia,
// and neither belongs on a page whose whole job is to make a place look
// worth going to. They stay out of /destinations and stay in the planner,
// which the catalogue's own empty state already allows for: "We haven't
// added that country yet. Tell us the place and we'll plan around it."
//
// Move one out of here as soon as it has a hero image and city images under
// /images/cities/<slug>/. test-city-uniqueness.ts fails if a planner country
// is neither profiled nor named here, so this list cannot rot quietly.
export const CATALOGUE_PENDING = new Set(["malaysia", "georgia", "russia"]);

export const countryGuides: CountryGuide[] = travelCountries.flatMap((country) => {
  const profile = profiles[country.value];
  if (!profile) {
    if (CATALOGUE_PENDING.has(country.value)) return [];
    throw new Error(`Missing destination profile for ${country.value}`);
  }
  const cities = country.cities.filter((city) => !city.value.startsWith("other-")).map((city) => {
    const detail = cityDetails[`${country.value}/${city.value}`];
    const fallback = fallbackPlaces(city.en, city.ar);
    return {
      slug: city.value,
      nameEn: city.en,
      nameAr: city.ar,
      image: `/images/cities/${country.value}/${city.value}.webp`,
      introEn: detail?.introEn ?? `${city.en} offers a distinct way into ${country.en}, with its own rhythm, neighbourhoods and memorable local experiences.`,
      introAr: detail?.introAr ?? `تمنحك ${city.ar} مدخلًا مختلفًا إلى ${country.ar} بإيقاعها وأحيائها وتجاربها المحلية المميزة.`,
      placesEn: detail?.placesEn ?? fallback.en,
      placesAr: detail?.placesAr ?? fallback.ar,
      days: detail?.days ?? "3–5",
    };
  });
  return [{ slug: country.value, nameEn: country.en, nameAr: country.ar, aliases: country.aliases, ...profile, cities }];
});

export const countryGuideBySlug = (slug: string) => countryGuides.find((country) => country.slug === slug);
export const cityGuideBySlug = (countrySlug: string, citySlug: string) => countryGuideBySlug(countrySlug)?.cities.find((city) => city.slug === citySlug);

export const legacyDestinationRoutes: Record<string, { country: string; city: string }> = {
  alula: { country: "saudi-arabia", city: "alula" }, riyadh: { country: "saudi-arabia", city: "riyadh" }, "jeddah-red-sea": { country: "saudi-arabia", city: "jeddah" }, "abha-aseer": { country: "saudi-arabia", city: "abha" },
  uae: { country: "uae", city: "dubai" }, istanbul: { country: "turkey", city: "istanbul" }, paris: { country: "france", city: "paris" }, switzerland: { country: "switzerland", city: "interlaken" }, london: { country: "united-kingdom", city: "london" }, italy: { country: "italy", city: "rome" }, spain: { country: "spain", city: "barcelona" }, austria: { country: "austria", city: "vienna" }, greece: { country: "greece", city: "athens" }, japan: { country: "japan", city: "tokyo" }, thailand: { country: "thailand", city: "bangkok" }, indonesia: { country: "indonesia", city: "bali" }, maldives: { country: "maldives", city: "north-male" }, "united-states": { country: "united-states", city: "new-york" }, canada: { country: "canada", city: "toronto" }, australia: { country: "australia", city: "sydney" },
};
