// Rich, editorial city guides for flagship destinations. Unlike the generic
// city guide (destination-guide-data.ts), entries here get their own
// distinct page template — see components/flagship-city-guide-page.tsx.
// A city with no entry here simply falls back to the generic template.

export type FlagshipPlace = {
  nameEn: string;
  nameAr: string;
  categoryEn: string;
  categoryAr: string;
  descriptionEn: string;
  descriptionAr: string;
  badgeEn?: string;
  badgeAr?: string;
  image?: string;
};

export type FlagshipDining = {
  nameEn: string;
  nameAr: string;
  cuisineEn: string;
  cuisineAr: string;
  descriptionEn: string;
  descriptionAr: string;
  image?: string;
};

export type FlagshipStay = {
  nameEn: string;
  nameAr: string;
  descriptionEn: string;
  descriptionAr: string;
  image?: string;
};

export type FlagshipWeatherWindow = {
  labelEn: string;
  labelAr: string;
  monthsEn: string;
  monthsAr: string;
  tempEn: string;
  tempAr: string;
  noteEn: string;
  noteAr: string;
};

export type FlagshipDayBeat = {
  timeEn: string;
  timeAr: string;
  placeEn: string;
  placeAr: string;
  descriptionEn: string;
  descriptionAr: string;
};

export type FlagshipCityGuide = {
  // Omit for the default leisure/excitement framing. Use "worship" for
  // pilgrimage cities (Makkah, Madinah) to swap section headings, drop the
  // dining/sample-day sections, and use respectful, practical CTA copy.
  tone?: "worship";
  storyEn: string[];
  storyAr: string[];
  pullQuoteEn: string;
  pullQuoteAr: string;
  weather: {
    bestWindow: FlagshipWeatherWindow;
    peakHeat: FlagshipWeatherWindow;
    tipEn: string;
    tipAr: string;
  };
  attractions: FlagshipPlace[];
  dining: FlagshipDining[];
  stay: FlagshipStay[];
  sampleDay: FlagshipDayBeat[];
};

const flagshipCityGuides: Record<string, FlagshipCityGuide> = {
  "saudi-arabia/riyadh": {
    storyEn: [
      "Two centuries ago, Riyadh was a walled town of mudbrick alleys inside the oasis of Diriyah, a seat of power, faith and trade at the heart of the Najd. Today it is one of the fastest-changing capitals on earth, and both versions of the city are still standing, a few kilometres apart.",
      "Spend a morning in At-Turaif, where the sun-dried walls of the first Saudi state have been carefully restored, and an evening under the glass sky bridge of Kingdom Centre, 300 metres above the same ground. In between: a dining scene now drawing chefs from Paris and Tokyo, an entertainment district built at giga-project scale, and a desert that is never more than a short drive from wherever you're standing.",
      "This is a first look at what a few days in Riyadh could hold. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "قبل قرنين من الزمن، كانت الرياض بلدة مسوّرة بأزقة من الطين داخل واحة الدرعية، مركزًا للسلطة والإيمان والتجارة في قلب نجد. واليوم أصبحت واحدة من أسرع عواصم العالم تحوّلًا، ولا تزال نسختا المدينة قائمتين على بعد كيلومترات قليلة من بعضهما.",
      "اقضِ صباحًا في حي الطريف حيث رُممت جدران الدولة السعودية الأولى الطينية بعناية، ثم أمسية تحت الجسر الزجاجي لبرج المملكة على ارتفاع 300 متر فوق الأرض ذاتها. وبينهما، مشهد طعام يجذب اليوم طهاة من باريس وطوكيو، وحيّ ترفيهي بُني بمقياس المشاريع العملاقة، وصحراء لا تبعد أبدًا أكثر من دقائق قليلة أينما كنت.",
      "هذه لمحة أولى عمّا يمكن أن تحمله أيام قليلة في الرياض. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Some cities show you their history. Riyadh lets you walk through it, then hands you a rollercoaster that didn't exist a year ago.",
    pullQuoteAr: "بعض المدن تُريك تاريخها. الرياض تتركك تمشي داخله، ثم تمنحك أفعوانية لم تكن موجودة قبل عام.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – March",
        monthsAr: "نوفمبر – مارس",
        tempEn: "22–29°C, dry and pleasant",
        tempAr: "22–29°م، أجواء جافة ولطيفة",
        noteEn: "Riyadh's cool season, comfortable for walking Diriyah and Boulevard World in the evenings.",
        noteAr: "موسم الرياض المعتدل، مناسب للتجول في الدرعية والبوليفارد وورلد مساءً.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – August",
        monthsAr: "يونيو – أغسطس",
        tempEn: "Up to 45°C, very dry",
        tempAr: "حتى 45°م، جو جاف جدًا",
        noteEn: "Plan around air-conditioned museums and evening hours; keep midday outdoor time short.",
        noteAr: "خطط حول المتاحف المكيفة والساعات المسائية، واجعل وقت الظهيرة في الخارج قصيرًا.",
      },
      tipEn: "Riyadh gets almost no rain year-round, pack for sun and dry heat even in winter.",
      tipAr: "لا تشهد الرياض أمطارًا تقريبًا طوال العام، فاستعد للشمس والجو الجاف حتى في الشتاء.",
    },
    attractions: [
      {
        nameEn: "Diriyah & At-Turaif",
        nameAr: "الدرعية وحي الطريف",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "The birthplace of the first Saudi state, with restored mudbrick walls and a UNESCO World Heritage skyline at dusk.",
        descriptionAr: "مهد الدولة السعودية الأولى، جدران طينية مرممة وأفق مسجل في التراث العالمي لليونسكو عند الغروب.",
      },
      {
        nameEn: "National Museum & Al Murabba",
        nameAr: "المتحف الوطني والمربع",
        categoryEn: "Culture",
        categoryAr: "ثقافة",
        descriptionEn: "Saudi history end to end, a short walk from the palaces of the historic Al Murabba district.",
        descriptionAr: "تاريخ السعودية كاملًا، على بعد خطوات من قصور حي المربع التاريخي.",
      },
      {
        nameEn: "Kingdom Centre & KAFD",
        nameAr: "برج المملكة ومركز الملك عبدالله المالي",
        categoryEn: "Skyline",
        categoryAr: "أفق المدينة",
        descriptionEn: "The city's signature glass sky bridge, 300 metres up, with the new financial district glittering beyond.",
        descriptionAr: "الجسر الزجاجي الشهير على ارتفاع 300 متر، وحي مالي جديد يلمع خلفه.",
      },
      {
        nameEn: "Six Flags Qiddiya City",
        nameAr: "سيكس فلاغز القدية",
        categoryEn: "Entertainment",
        categoryAr: "ترفيه",
        descriptionEn: "Opened December 2025, Six Flags' first park outside North America, home to Falcons Flight, the world's tallest, fastest coaster. About 40 minutes from central Riyadh.",
        descriptionAr: "افتُتحت في ديسمبر 2025، أول منتزه لسيكس فلاغز خارج أمريكا الشمالية، وتضم لعبة Falcons Flight الأعلى والأسرع في العالم، على بعد نحو 40 دقيقة من وسط الرياض.",
        badgeEn: "Newly opened",
        badgeAr: "افتُتح حديثًا",
      },
      {
        nameEn: "AquaRabia",
        nameAr: "أكوارابيا",
        categoryEn: "Family",
        categoryAr: "عائلي",
        descriptionEn: "The region's largest water park, opened April 2026 in Qiddiya, with 22 rides including four world-record attractions.",
        descriptionAr: "أكبر منتزه مائي في المنطقة، افتُتح في أبريل 2026 في القدية، ويضم 22 لعبة من بينها أربع ألعاب حائزة على أرقام قياسية عالمية.",
        badgeEn: "Newly opened",
        badgeAr: "افتُتح حديثًا",
      },
      {
        nameEn: "Boulevard World",
        nameAr: "بوليفارد وورلد",
        categoryEn: "Seasonal",
        categoryAr: "موسمي",
        descriptionEn: "24 country-themed zones, the world's largest artificial lake and submarine rides. Open seasonally during Riyadh Season, so check dates before you plan around it.",
        descriptionAr: "24 منطقة بطابع دول مختلفة، وأكبر بحيرة اصطناعية في العالم ورحلات غواصات، ويعمل موسميًا خلال موسم الرياض، لذا تحقق من المواعيد قبل التخطيط حوله.",
      },
    ],
    dining: [
      {
        nameEn: "La Petite Maison",
        nameAr: "لا بوتيت ميزون",
        cuisineEn: "French",
        cuisineAr: "فرنسي",
        descriptionEn: "An award-winning Riyadh outpost of the acclaimed French bistro group, in the heart of Olaya.",
        descriptionAr: "فرع الرياض الحائز على جوائز لمجموعة المطاعم الفرنسية الشهيرة، في قلب حي العليا.",
      },
      {
        nameEn: "Myazu",
        nameAr: "مايازو",
        cuisineEn: "Japanese",
        cuisineAr: "ياباني",
        descriptionEn: "Precision Japanese cooking ranked among MENA's 50 Best Restaurants.",
        descriptionAr: "مطبخ ياباني متقن ضمن قائمة أفضل 50 مطعمًا في الشرق الأوسط وشمال أفريقيا.",
      },
      {
        nameEn: "Porter House",
        nameAr: "بورتر هاوس",
        cuisineEn: "Steakhouse",
        cuisineAr: "ستيك هاوس",
        descriptionEn: "Classic New York steakhouse spirit with globally sourced beef, in a sleek Olaya setting.",
        descriptionAr: "أجواء ستيك هاوس نيويوركية أصيلة ولحوم مختارة عالميًا، في أجواء أنيقة بحي العليا.",
      },
      {
        nameEn: "Yauatcha",
        nameAr: "ياواتشا",
        cuisineEn: "Dim sum",
        cuisineAr: "ديم سم",
        descriptionEn: "Refined Cantonese dim sum from the team behind Hakkasan.",
        descriptionAr: "ديم سم كانتوني راقٍ من فريق مطعم هاكاسان الشهير.",
      },
    ],
    stay: [
      {
        nameEn: "Four Seasons Hotel Riyadh at Kingdom Centre",
        nameAr: "فندق فور سيزونز الرياض في برج المملكة",
        descriptionEn: "Floors 30 to 50 of the Kingdom Centre tower, with the city's skyline as a permanent backdrop.",
        descriptionAr: "يشغل الطوابق من 30 إلى 50 في برج المملكة، وأفق المدينة خلفية دائمة له.",
      },
      {
        nameEn: "The Ritz-Carlton, Riyadh",
        nameAr: "ريتز كارلتون الرياض",
        descriptionEn: "52 acres of landscaped gardens in the Diplomatic Quarter, one of the most decorated hotels in the Kingdom.",
        descriptionAr: "حدائق مصممة على مساحة 52 فدانًا في حي السفارات، وأحد أكثر الفنادق حصولًا على تكريمات في المملكة.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "At-Turaif",
        placeAr: "حي الطريف",
        descriptionEn: "The mudbrick walls of the first Saudi state, quiet before the heat sets in.",
        descriptionAr: "جدران الدولة السعودية الأولى الطينية، هادئة قبل اشتداد الحر.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Kingdom Centre Sky Bridge",
        placeAr: "الجسر الزجاجي لبرج المملكة",
        descriptionEn: "300 metres up, watching the city turn gold.",
        descriptionAr: "على ارتفاع 300 متر، وأنت تشاهد المدينة تتحول إلى الذهبي.",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "A table at Myazu",
        placeAr: "طاولة في مايازو",
        descriptionEn: "Precision Japanese cooking to close the day.",
        descriptionAr: "مطبخ ياباني متقن يختم اليوم.",
      },
    ],
  },
  "saudi-arabia/jeddah": {
    storyEn: [
      "Jeddah has always been a gateway. For over a thousand years, pilgrims arrived by sea here before travelling on to Makkah, and the city grew rich on that role, coral-stone merchant houses rising along streets built for trade, not tourists.",
      "That old town, Al-Balad, is still standing, its wooden balconies restored one building at a time. A short drive away, the Corniche runs 30 kilometres along the Red Sea, past the world's tallest fountain and a waterfront now lined with restaurants from Rome, Seoul and beyond. Jeddah doesn't choose between its two identities, historic trading post and Red Sea social capital, it simply runs both at once.",
      "This is a first look at what a few days here could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "كانت جدة دائمًا بوابة. لأكثر من ألف عام، وصل الحجاج عبر البحر إلى هنا قبل التوجه إلى مكة، ونمت المدينة وازدهرت بهذا الدور، وارتفعت بيوت التجار المبنية بالحجر المرجاني على شوارع صُممت للتجارة لا للسياحة.",
      "تلك المدينة القديمة، البلد، ما زالت قائمة، وتُرمَّم شرفاتها الخشبية مبنى تلو الآخر. وعلى بعد دقائق، يمتد الكورنيش 30 كيلومترًا على طول البحر الأحمر، متجاوزًا أطول نافورة في العالم وواجهة بحرية تصطف عليها اليوم مطاعم من روما وسيول وما وراءهما. جدة لا تختار بين هويتيها، محطة تجارية تاريخية وعاصمة اجتماعية على البحر الأحمر، بل تعيشهما معًا.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة هنا. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "This coast has welcomed pilgrims for over a thousand years. Now it's welcoming chefs from three continents, all facing the same sea.",
    pullQuoteAr: "استقبل هذا الساحل الحجاج لأكثر من ألف عام. واليوم يستقبل طهاة من ثلاث قارات، جميعهم يطلّون على البحر ذاته.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – March",
        monthsAr: "نوفمبر – مارس",
        tempEn: "28–30°C, warm and pleasant",
        tempAr: "28–30°م، دافئة ولطيفة",
        noteEn: "Comfortable for the Corniche and Al-Balad's narrow streets in the evenings.",
        noteAr: "مناسب للتجول في الكورنيش وأزقة البلد الضيقة مساءً.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – September",
        monthsAr: "يونيو – سبتمبر",
        tempEn: "Up to 39°C, hot and humid",
        tempAr: "حتى 39°م، حار ورطب",
        noteEn: "Coastal humidity makes it feel heavier than the number suggests; keep to shaded, air-conditioned hours.",
        noteAr: "الرطوبة الساحلية تجعل الحر أثقل مما توحي به الأرقام، فخطط لوقتك في الأماكن المظللة والمكيفة.",
      },
      tipEn: "Jeddah's Red Sea humidity makes the heat feel heavier here than inland Riyadh, even at similar temperatures.",
      tipAr: "رطوبة البحر الأحمر في جدة تجعل الحر أثقل من الرياض حتى عند تقارب درجات الحرارة.",
    },
    attractions: [
      {
        nameEn: "Al-Balad",
        nameAr: "البلد",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Jeddah's UNESCO-listed old town, coral-stone merchant houses with carved wooden balconies, still mid-restoration in places.",
        descriptionAr: "المدينة القديمة في جدة المسجلة في تراث اليونسكو، بيوت تجارية من الحجر المرجاني بشرفات خشبية منحوتة، ولا تزال قيد الترميم في بعض الأجزاء.",
      },
      {
        nameEn: "Jeddah Corniche & King Fahd Fountain",
        nameAr: "كورنيش جدة ونافورة الملك فهد",
        categoryEn: "Waterfront",
        categoryAr: "واجهة بحرية",
        descriptionEn: "A 30-kilometre Red Sea promenade anchored by the world's tallest fountain, spraying seawater over 260 metres up.",
        descriptionAr: "ممشى بحري يمتد 30 كيلومترًا على البحر الأحمر، وتتوسطه أطول نافورة في العالم التي تقذف المياه لأكثر من 260 مترًا.",
      },
      {
        nameEn: "Red Sea diving & boat days",
        nameAr: "الغوص ورحلات البحر الأحمر",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "Coral reefs a short boat ride from the city, among the most accessible diving in the Kingdom.",
        descriptionAr: "شعاب مرجانية على بعد رحلة قصيرة بالقارب من المدينة، من أسهل مواقع الغوص وصولًا في المملكة.",
      },
      {
        nameEn: "Jeddah Waterfront",
        nameAr: "واجهة جدة البحرية",
        categoryEn: "Skyline",
        categoryAr: "أفق المدينة",
        descriptionEn: "A newer stretch of the Corniche, home to the city's most ambitious restaurant openings and Red Sea views.",
        descriptionAr: "امتداد أحدث من الكورنيش، يضم أبرز افتتاحات المطاعم في المدينة وإطلالات على البحر الأحمر.",
      },
    ],
    dining: [
      {
        nameEn: "San Carlo",
        nameAr: "سان كارلو",
        cuisineEn: "Italian",
        cuisineAr: "إيطالي",
        descriptionEn: "The most reliable address in the city for Italian cooking, in a polished Corniche-adjacent setting.",
        descriptionAr: "العنوان الأكثر ثباتًا في المدينة للمطبخ الإيطالي، في أجواء أنيقة قريبة من الكورنيش.",
      },
      {
        nameEn: "Sura",
        nameAr: "سورا",
        cuisineEn: "Korean",
        cuisineAr: "كوري",
        descriptionEn: "Jeddah's best-regarded Korean fine dining, precise and polished.",
        descriptionAr: "أبرز مطاعم المطبخ الكوري الراقي في جدة، بدقة وأناقة.",
      },
      {
        nameEn: "Sultan's Steakhouse",
        nameAr: "سلطانز ستيك هاوس",
        cuisineEn: "Steakhouse",
        cuisineAr: "ستيك هاوس",
        descriptionEn: "A steakhouse and grill built around globally sourced cuts, popular after a fountain-side walk.",
        descriptionAr: "مطعم شواء وستيك يعتمد على لحوم مختارة عالميًا، وجهة مفضلة بعد نزهة قرب النافورة.",
      },
      {
        nameEn: "Lusin",
        nameAr: "لوسين",
        cuisineEn: "Armenian",
        cuisineAr: "أرمني",
        descriptionEn: "Middle Eastern and Armenian cooking in a warm, unhurried setting.",
        descriptionAr: "مطبخ شرق أوسطي وأرمني في أجواء دافئة وهادئة.",
      },
    ],
    stay: [
      {
        nameEn: "Four Seasons Hotel Jeddah at the Corniche",
        nameAr: "فندق فور سيزونز جدة على الكورنيش",
        descriptionEn: "The city's top-rated address, an infinity pool and Corniche views on the North Corniche.",
        descriptionAr: "العنوان الأعلى تقييمًا في المدينة، بمسبح لا متناهٍ وإطلالات على الكورنيش الشمالي.",
      },
      {
        nameEn: "Rosewood Jeddah",
        nameAr: "روزوود جدة",
        descriptionEn: "Modern elegance and traditional Arabian hospitality, also on the North Corniche.",
        descriptionAr: "أناقة عصرية وضيافة عربية أصيلة، على الكورنيش الشمالي أيضًا.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Al-Balad",
        placeAr: "البلد",
        descriptionEn: "Wander the coral-stone streets before the day's heat arrives.",
        descriptionAr: "تجوّل في أزقة الحجر المرجاني قبل اشتداد حر النهار.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "King Fahd Fountain",
        placeAr: "نافورة الملك فهد",
        descriptionEn: "A Corniche walk as the fountain lights up against the Red Sea sky.",
        descriptionAr: "نزهة على الكورنيش بينما تُضاء النافورة أمام سماء البحر الأحمر.",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "Dinner at San Carlo",
        placeAr: "عشاء في سان كارلو",
        descriptionEn: "Italian cooking to close the day, minutes from the water.",
        descriptionAr: "مطبخ إيطالي يختم اليوم، على بعد دقائق من البحر.",
      },
    ],
  },
  "saudi-arabia/alula": {
    storyEn: [
      "AlUla spent centuries as a waypoint, caravans passing through on the incense route, then the Nabataeans carving more than a hundred tombs into its sandstone cliffs at Hegra, the first place in Saudi Arabia to be named a UNESCO World Heritage Site.",
      "The Kingdom has spent the last several years turning that history into one of its most carefully designed destinations: boutique desert resorts tucked into Ashar Valley, a concert hall built as the world's largest mirrored building, and dinners served at the edge of canyons that didn't have a restaurant a decade ago. AlUla rewards travellers who want depth over volume, a handful of unforgettable days rather than a checklist.",
      "This is a first glimpse of what your time in AlUla could hold. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "كانت العلا لقرون محطة عبور، تمر بها القوافل على طريق البخور، ثم نحت الأنباط أكثر من مئة مقبرة في منحدراتها الرملية في الحِجر، أول موقع في السعودية يُسجَّل في التراث العالمي لليونسكو.",
      "أمضت المملكة السنوات الأخيرة تحوّل هذا التاريخ إلى واحدة من أكثر وجهاتها دقة في التصميم، منتجعات صحراوية فاخرة في وادي عشار، وقاعة حفلات بُنيت كأكبر مبنى مرآوي في العالم، وعشاء يُقدَّم على حافة أودية لم يكن بها مطعم قبل عقد من الزمن. تكافئ العلا من يبحث عن العمق لا الكم، أيامًا قليلة لا تُنسى بدل قائمة طويلة من المحطات.",
      "هذه لمحة أولى عمّا يمكن أن تحمله أيامك في العلا. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Two thousand years ago, someone carved a tomb into these cliffs and believed it would outlast them. It did, and today the same valley serves dinner with a view of it.",
    pullQuoteAr: "قبل ألفي عام، نحت أحدهم مقبرة في هذه المنحدرات مؤمنًا بأنها ستبقى بعده. وقد بقيت، واليوم يُقدَّم العشاء في الوادي ذاته وأنت تطل عليها.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – March",
        monthsAr: "نوفمبر – مارس",
        tempEn: "20–27°C by day, near freezing at night",
        tempAr: "20–27°م نهارًا، قريبة من الصفر ليلًا",
        noteEn: "Ideal for walking Hegra and Elephant Rock; bring a jacket for after dark.",
        noteAr: "مثالية للتجول في الحِجر وجبل الفيل، فاصطحب سترة دافئة لليل.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – September",
        monthsAr: "يونيو – سبتمبر",
        tempEn: "Over 40°C, hot and dry",
        tempAr: "أكثر من 40°م، حار وجاف",
        noteEn: "Most outdoor sites are best visited early morning or after sunset.",
        noteAr: "يُفضَّل زيارة المواقع الخارجية في الصباح الباكر أو بعد الغروب.",
      },
      tipEn: "AlUla's desert nights swing much colder than the daytime heat suggests, pack layers even in winter.",
      tipAr: "ليالي العلا الصحراوية أبرد بكثير مما توحي به حرارة النهار، فاصطحب طبقات دافئة حتى في الشتاء.",
    },
    attractions: [
      {
        nameEn: "Hegra",
        nameAr: "الحِجر",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Saudi Arabia's first UNESCO World Heritage Site, more than 110 monumental Nabataean tombs carved into sandstone.",
        descriptionAr: "أول موقع تراث عالمي لليونسكو في السعودية، أكثر من 110 مقابر نبطية ضخمة منحوتة في الصخر الرملي.",
      },
      {
        nameEn: "Elephant Rock",
        nameAr: "جبل الفيل",
        categoryEn: "Landmark",
        categoryAr: "معلم",
        descriptionEn: "A 52-metre sandstone formation shaped by wind over millions of years, AlUla's most recognisable sight.",
        descriptionAr: "تكوين رملي بارتفاع 52 مترًا شكّلته الرياح عبر ملايين السنين، أشهر معالم العلا.",
      },
      {
        nameEn: "Maraya",
        nameAr: "مرايا",
        categoryEn: "Culture",
        categoryAr: "ثقافة",
        descriptionEn: "The world's largest mirrored building, reflecting the desert around it, home to concerts and destination dining.",
        descriptionAr: "أكبر مبنى مرآوي في العالم، يعكس الصحراء من حوله، ويستضيف الحفلات ومطاعم استثنائية.",
      },
      {
        nameEn: "AlUla Old Town",
        nameAr: "بلدة العلا القديمة",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Mudbrick lanes at the foot of the oasis, once the region's trading and pilgrimage crossroads.",
        descriptionAr: "أزقة طينية عند سفح الواحة، كانت يومًا ملتقى القوافل التجارية والحجاج.",
      },
      {
        nameEn: "Sharaan Nature Reserve",
        nameAr: "محمية شرعان الطبيعية",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "A protected canyon landscape reintroducing native wildlife, best experienced at dawn or dusk.",
        descriptionAr: "محمية طبيعية في الأودية تعيد توطين الحياة البرية المحلية، وتُزار غالبًا عند الفجر أو الغروب.",
      },
    ],
    dining: [
      {
        nameEn: "Maraya Social",
        nameAr: "مرايا سوشال",
        cuisineEn: "Contemporary",
        cuisineAr: "عصري",
        descriptionEn: "Chef Jason Atherton's restaurant atop the mirrored building, local produce in his signature style.",
        descriptionAr: "مطعم الشيف جيسون أذرتون فوق المبنى المرآوي، منتجات محلية بأسلوبه المميز.",
      },
      {
        nameEn: "OKTO",
        nameAr: "أوكتو",
        cuisineEn: "Greek",
        cuisineAr: "يوناني",
        descriptionEn: "Mediterranean flavours perched at Harrat Viewpoint, a favourite for sunset dinners.",
        descriptionAr: "نكهات متوسطية على إطلالة الحرة، وجهة مفضلة لعشاء الغروب.",
      },
      {
        nameEn: "Circolo",
        nameAr: "شيركولو",
        cuisineEn: "Italian",
        cuisineAr: "إيطالي",
        descriptionEn: "Wood-fired pizza and small plates on the edge of the oasis, with valley and mountain views.",
        descriptionAr: "بيتزا مخبوزة على الحطب وأطباق صغيرة عند حافة الواحة، بإطلالات على الوادي والجبال.",
      },
      {
        nameEn: "Hegra Visitor Centre hospitality",
        nameAr: "ضيافة مركز زوار الحِجر",
        cuisineEn: "Traditional",
        cuisineAr: "تقليدي",
        descriptionEn: "Dates, dried fruit and Saudi coffee served the traditional way before you enter the tombs.",
        descriptionAr: "تمر وفواكه مجففة وقهوة سعودية تُقدَّم بالطريقة التقليدية قبل دخول المقابر.",
      },
    ],
    stay: [
      {
        nameEn: "Banyan Tree AlUla",
        nameAr: "بانيان تري العلا",
        descriptionEn: "An all-villa desert sanctuary in Ashar Valley, most villas with a private pool.",
        descriptionAr: "ملاذ صحراوي بفلل كاملة في وادي عشار، ومعظمها بمسبح خاص.",
      },
      {
        nameEn: "Our Habitas AlUla",
        nameAr: "هابيتاس العلا",
        descriptionEn: "Set among the sandstone rocks of Ashar Valley, a favourite for first-time visitors to AlUla.",
        descriptionAr: "يقع بين صخور وادي عشار الرملية، وجهة مفضلة لزوار العلا لأول مرة.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Hegra",
        placeAr: "الحِجر",
        descriptionEn: "Walk among the tombs before the desert heat builds.",
        descriptionAr: "تجوّل بين المقابر قبل اشتداد حر الصحراء.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Elephant Rock",
        placeAr: "جبل الفيل",
        descriptionEn: "Watch the sandstone change colour as the sun drops.",
        descriptionAr: "شاهد الصخر الرملي يتغير لونه مع غروب الشمس.",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "Dinner at Maraya Social",
        placeAr: "عشاء في مرايا سوشال",
        descriptionEn: "A table atop the world's largest mirrored building to close the day.",
        descriptionAr: "طاولة فوق أكبر مبنى مرآوي في العالم لتختم بها يومك.",
      },
    ],
  },
  "saudi-arabia/makkah": {
    tone: "worship",
    storyEn: [
      "Makkah is the direction of prayer five times a day for two billion people, and for many travellers, standing before the Kaaba for the first time is a moment years in the making. This guide exists for one reason, to help the practical parts of that journey go smoothly, so your attention can stay where it belongs.",
      "Entry to Makkah is restricted to Muslims, every road into the city has a checkpoint, and the correct visa and Nusuk permit matter as much as your flight. Once you're here, the Masjid al-Haram sits at the centre of everything, hotels, transport and the day's rhythm all orient around it.",
      "Tell us your dates, who's travelling with you and whether this is Umrah or a longer visit, and we'll help arrange the details around your worship.",
    ],
    storyAr: [
      "مكة هي قِبلة الصلاة خمس مرات يوميًا لملياري إنسان، وبالنسبة لكثير من المسافرين، فإن الوقوف أمام الكعبة لأول مرة لحظة استغرق التحضير لها سنوات. هذا الدليل موجود لسبب واحد، مساعدتك في تسهيل الجوانب العملية من هذه الرحلة، حتى يبقى تركيزك حيث ينبغي أن يكون.",
      "دخول مكة مقتصر على المسلمين، وعلى كل طريق مؤدٍ إلى المدينة نقطة تفتيش، والتأشيرة الصحيحة وتصريح نُسُك لا يقلان أهمية عن تذكرة طيرانك. وبمجرد وصولك، يكون المسجد الحرام مركز كل شيء، فالفنادق والتنقل وإيقاع يومك كلها تدور حوله.",
      "أخبرنا بتواريخك ومن سيرافقك وما إذا كانت هذه رحلة عمرة أو زيارة أطول، وسنساعدك في ترتيب التفاصيل حول عبادتك.",
    ],
    pullQuoteEn: "For many, this is a journey planned for years and lived in a single moment. Everything else is logistics.",
    pullQuoteAr: "بالنسبة للكثيرين، هذه رحلة يُخطَّط لها سنوات وتُعاش في لحظة واحدة. وكل ما عداها مجرد تفاصيل تنظيمية.",
    weather: {
      bestWindow: {
        labelEn: "Most manageable months",
        labelAr: "أكثر الأشهر اعتدالًا",
        monthsEn: "January – March",
        monthsAr: "يناير – مارس",
        tempEn: "30–35°C, still warm",
        tempAr: "30–35°م، لا تزال دافئة",
        noteEn: "The most comfortable window for walking to and from the Haram; still warm by most standards.",
        noteAr: "الفترة الأكثر راحة للمشي من وإلى الحرم والعودة إليه، مع أنها لا تزال دافئة.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – August",
        monthsAr: "يونيو – أغسطس",
        tempEn: "Up to 44°C, extreme heat",
        tempAr: "حتى 44°م، حر شديد",
        noteEn: "Outdoor time between prayers is genuinely demanding; prioritise shaded routes and stay hydrated.",
        noteAr: "الوقت في الخارج بين الصلوات يكون شاقًا فعليًا، فاختر المسارات المظللة واحرص على شرب الماء باستمرار.",
      },
      tipEn: "Makkah stays warm even in its coolest months, and Hajj dates shift earlier each Gregorian year, so always check the season before you plan.",
      tipAr: "تبقى مكة دافئة حتى في أبرد أشهرها، ومواعيد الحج تتقدم كل عام ميلادي، لذا تحقق دائمًا من الموسم قبل التخطيط.",
    },
    attractions: [
      {
        nameEn: "Masjid al-Haram & the Kaaba",
        nameAr: "المسجد الحرام والكعبة",
        categoryEn: "The Haram",
        categoryAr: "الحرم",
        descriptionEn: "The centre of Islam and the direction of prayer for Muslims worldwide, home to the Kaaba and the Zamzam well.",
        descriptionAr: "مركز الإسلام وقِبلة المسلمين في أنحاء العالم، ويضم الكعبة المشرفة وبئر زمزم.",
      },
      {
        nameEn: "Jabal al-Nour & the Cave of Hira",
        nameAr: "جبل النور وغار حراء",
        categoryEn: "Sacred history",
        categoryAr: "تاريخ مقدس",
        descriptionEn: "A steep climb above the city to the cave associated with the first revelation, a popular walk for visiting pilgrims.",
        descriptionAr: "صعود شديد فوق المدينة إلى الغار المرتبط ببدء الوحي، ومسار مفضل لدى الحجاج الزائرين.",
      },
      {
        nameEn: "Jabal Thawr",
        nameAr: "جبل ثور",
        categoryEn: "Sacred history",
        categoryAr: "تاريخ مقدس",
        descriptionEn: "The mountain south of the Haram associated with the Hijrah, still visited by pilgrims with time to spare.",
        descriptionAr: "الجبل الواقع جنوب الحرم والمرتبط بالهجرة، ولا يزال يزوره الحجاج ممن لديهم وقت إضافي.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Fairmont Makkah Clock Royal Tower",
        nameAr: "فيرمونت مكة كلوك رويال تاور",
        descriptionEn: "Two minutes' walk from Masjid al-Haram, among the closest hotels to the Kaaba.",
        descriptionAr: "على بعد دقيقتين مشيًا من المسجد الحرام، من أقرب الفنادق إلى الكعبة.",
      },
      {
        nameEn: "Raffles Makkah Palace",
        nameAr: "رافلز مكة بالاس",
        descriptionEn: "An all-suite hotel directly adjoining the Haram, with 24-hour personal butler service.",
        descriptionAr: "فندق بأجنحة كاملة يلاصق الحرم مباشرة، مع خدمة الخادم الشخصي على مدار الساعة.",
      },
    ],
    sampleDay: [],
  },
  "saudi-arabia/madinah": {
    tone: "worship",
    storyEn: [
      "Madinah is where the Prophet Muhammad settled after the Hijrah, and where he is buried beneath the green dome that now marks the skyline. Unlike Makkah, the city itself is open to non-Muslim visitors, but entry to Al-Masjid an-Nabawi, the Prophet's Mosque, remains for Muslims only.",
      "Most journeys here are unhurried. Pilgrims often pair Madinah with Makkah on the same trip, and the city rewards a slower pace, prayers at the mosque, a walk to Quba, the first mosque built in Islam, and a quiet afternoon at Uhud, where the Prophet's companions are buried.",
      "Tell us your dates, who's travelling with you and how this fits alongside the rest of your journey, and we'll help arrange the details around your visit.",
    ],
    storyAr: [
      "المدينة المنورة هي حيث استقر النبي محمد صلى الله عليه وسلم بعد الهجرة، وحيث دُفن تحت القبة الخضراء التي تميز أفق المدينة اليوم. وخلافًا لمكة، فإن المدينة نفسها مفتوحة لغير المسلمين، لكن دخول المسجد النبوي يبقى مقتصرًا على المسلمين.",
      "غالبًا ما تكون الرحلات هنا هادئة وغير متعجلة. كثيرًا ما يجمع الحجاج بين المدينة ومكة في الرحلة ذاتها، وتكافئ المدينة من يتمهل، الصلاة في المسجد، ومشي إلى قباء أول مسجد بُني في الإسلام، وعصر هادئ عند أحد حيث دُفن صحابة النبي.",
      "أخبرنا بتواريخك ومن سيرافقك وكيف تتناسب هذه الزيارة مع بقية رحلتك، وسنساعدك في ترتيب التفاصيل حولها.",
    ],
    pullQuoteEn: "Whether it's a first visit or a fifth, the walk toward the green dome tends to go quiet in the same way each time.",
    pullQuoteAr: "سواء كانت هذه زيارتك الأولى أو الخامسة، فإن المشي نحو القبة الخضراء يخيّم عليه الهدوء ذاته في كل مرة.",
    weather: {
      bestWindow: {
        labelEn: "Most comfortable months",
        labelAr: "أكثر الأشهر راحة",
        monthsEn: "November – February",
        monthsAr: "نوفمبر – فبراير",
        tempEn: "25–28°C, mild and pleasant",
        tempAr: "25–28°م، معتدلة ولطيفة",
        noteEn: "Comfortable for walking to and from the mosque and visiting Quba and Uhud.",
        noteAr: "مناسبة للمشي من وإلى المسجد وزيارة قباء وأحد.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – August",
        monthsAr: "يونيو – أغسطس",
        tempEn: "Up to 43°C, very hot",
        tempAr: "حتى 43°م، حر شديد جدًا",
        noteEn: "Keep outdoor time between prayers short and stay hydrated.",
        noteAr: "اجعل وقتك في الخارج بين الصلوات قصيرًا واحرص على شرب الماء.",
      },
      tipEn: "Many travellers visit Madinah and Makkah on the same trip, plan the order around your dates and energy for each city.",
      tipAr: "يزور كثير من المسافرين المدينة ومكة في الرحلة نفسها، فخطط للترتيب بينهما حسب تواريخك وطاقتك في كل مدينة.",
    },
    attractions: [
      {
        nameEn: "Al-Masjid an-Nabawi",
        nameAr: "المسجد النبوي",
        categoryEn: "The Haram",
        categoryAr: "الحرم",
        descriptionEn: "The Prophet's Mosque, marked by the green dome, the second-holiest site in Islam. Entry is for Muslims only.",
        descriptionAr: "المسجد النبوي، الذي تميزه القبة الخضراء، ثاني أقدس موقع في الإسلام. الدخول مقتصر على المسلمين.",
      },
      {
        nameEn: "Quba Mosque",
        nameAr: "مسجد قباء",
        categoryEn: "Sacred history",
        categoryAr: "تاريخ مقدس",
        descriptionEn: "The first mosque built in Islam, and a short, popular visit from central Madinah.",
        descriptionAr: "أول مسجد بُني في الإسلام، وزيارة قصيرة ومحببة من وسط المدينة.",
      },
      {
        nameEn: "Mount Uhud",
        nameAr: "جبل أحد",
        categoryEn: "Sacred history",
        categoryAr: "تاريخ مقدس",
        descriptionEn: "Site of the Battle of Uhud, and the resting place of 70 of the Prophet's companions.",
        descriptionAr: "موقع غزوة أحد، ومقر دفن سبعين من صحابة النبي.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Pullman Zamzam Madinah",
        nameAr: "بولمان زمزم المدينة",
        descriptionEn: "Adjacent to Al-Masjid an-Nabawi, moments from the Al Salam Gate.",
        descriptionAr: "ملاصق للمسجد النبوي، على بعد خطوات من باب السلام.",
      },
      {
        nameEn: "Anwar Al Madinah Mövenpick",
        nameAr: "أنوار المدينة موڤنبيك",
        descriptionEn: "Two minutes from the Prophet's Mosque, with direct mall access.",
        descriptionAr: "على بعد دقيقتين من المسجد النبوي، مع وصول مباشر إلى المول.",
      },
    ],
    sampleDay: [],
  },
  "saudi-arabia/red-sea": {
    storyEn: [
      "Saudi Arabia's Red Sea coast runs for more than 1,800 kilometres, and most of its reef system has barely been touched by tourism. Where Egypt's coast has been dived for decades, this one is still being mapped, coral grottoes with hammerhead sharks, islands where whale sharks pass close to shore, and reef walls that stay unnervingly quiet.",
      "The Kingdom is building its answer to the world's best private-island destinations here, one resort at a time. St. Regis and Six Senses have opened on their own islands, Nujuma sits under Ritz-Carlton's most exclusive label, and a new adventure district, Adrena, just opened this year. This isn't a city you walk through, it's a coastline you disappear into.",
      "This is a first look at what a few days on the Red Sea could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "يمتد ساحل البحر الأحمر السعودي لأكثر من 1,800 كيلومتر، ومعظم نظامه المرجاني لم تلمسه السياحة بعد. فبينما غُطست سواحل مصر لعقود، لا يزال هذا الساحل قيد الاستكشاف، كهوف مرجانية يزورها سمك القرش أبو مطرقة، وجزر يمر بالقرب من شواطئها سمك القرش الحوتي، وجدران شعاب تبقى هادئة بشكل يثير الدهشة.",
      "تبني المملكة هنا إجابتها على أفضل وجهات الجزر الخاصة في العالم، منتجعًا تلو الآخر. افتتح سانت ريجس وسيكس سنسز على جزرهما الخاصة، وتحمل نجومة أرقى تصنيفات ريتز كارلتون، وافتُتح هذا العام حيّ مغامرات جديد يُدعى أدرينا. هذه ليست مدينة تمشي فيها، بل ساحل تختفي داخله.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة على البحر الأحمر. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Most of this reef system has never been dived by tourists. For once, \"untouched\" isn't just marketing language.",
    pullQuoteAr: "معظم هذا النظام المرجاني لم يغُصه سائح من قبل. ولمرة واحدة، فإن كلمة \"بكر\" ليست مجرد عبارة تسويقية.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – April",
        monthsAr: "نوفمبر – أبريل",
        tempEn: "24–32°C, warm with calm seas",
        tempAr: "24–32°م، دافئة وبحر هادئ",
        noteEn: "Diving conditions peak here, warm water, excellent visibility and calm crossings to the islands.",
        noteAr: "ظروف الغوص في أفضل حالاتها هنا، مياه دافئة ورؤية ممتازة وعبور هادئ إلى الجزر.",
      },
      peakHeat: {
        labelEn: "Hot season",
        labelAr: "الموسم الحار",
        monthsEn: "June – September",
        monthsAr: "يونيو – سبتمبر",
        tempEn: "Very hot and humid, warmest sea",
        tempAr: "حار ورطب جدًا، والبحر في أدفأ حالاته",
        noteEn: "Sea temperatures are at their warmest and resorts are quieter, but midday heat and humidity are intense.",
        noteAr: "درجة حرارة البحر في أعلى مستوياتها والمنتجعات أهدأ، لكن الحر والرطوبة في الظهيرة شديدان.",
      },
      tipEn: "Late October and early March offer the best balance, good weather without the peak-season crowds.",
      tipAr: "أواخر أكتوبر وأوائل مارس يقدمان أفضل توازن، طقس جيد من دون ازدحام موسم الذروة.",
    },
    attractions: [
      {
        nameEn: "Shura Island",
        nameAr: "جزيرة شورى",
        categoryEn: "Hub",
        categoryAr: "محور",
        descriptionEn: "The destination's main hub, home to several resorts including The Red Sea EDITION and InterContinental The Red Sea.",
        descriptionAr: "المحور الرئيسي للوجهة، ويضم عدة منتجعات من بينها ذا ريد سي إديشن وإنتركونتيننتال ذا ريد سي.",
      },
      {
        nameEn: "Al Lith Island",
        nameAr: "جزيرة الليث",
        categoryEn: "Diving",
        categoryAr: "غوص",
        descriptionEn: "White sand and shallow blue water for snorkelling, with whale sharks and large fish for advanced divers.",
        descriptionAr: "رمال بيضاء ومياه زرقاء ضحلة للسنوركل، ويشاهد الغواصون المتقدمون فيها القروش الحوتية وأسماكًا كبيرة.",
      },
      {
        nameEn: "Abu Galawa",
        nameAr: "أبو جلاوة",
        categoryEn: "Diving",
        categoryAr: "غوص",
        descriptionEn: "A coral grotto known for schools of sharks, including hammerheads.",
        descriptionAr: "كهف مرجاني يشتهر بأسراب من أسماك القرش، من بينها أبو مطرقة.",
      },
      {
        nameEn: "Adrena",
        nameAr: "أدرينا",
        categoryEn: "Entertainment",
        categoryAr: "ترفيه",
        descriptionEn: "A new adventure and entertainment district for the destination, opened in early 2026.",
        descriptionAr: "حيّ مغامرات وترفيه جديد للوجهة، افتُتح في أوائل 2026.",
        badgeEn: "Newly opened",
        badgeAr: "افتُتح حديثًا",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "The St. Regis Red Sea Resort",
        nameAr: "منتجع سانت ريجس البحر الأحمر",
        descriptionEn: "An artistic private-island stay, one of the destination's first resorts to open.",
        descriptionAr: "إقامة فنية على جزيرة خاصة، من أوائل منتجعات الوجهة افتتاحًا.",
      },
      {
        nameEn: "Six Senses Southern Dunes",
        nameAr: "سيكس سنسز ساذرن ديونز",
        descriptionEn: "Desert-meets-sea wellness resort, built into the dunes above the coastline.",
        descriptionAr: "منتجع عافية يجمع بين الصحراء والبحر، مبني بين الكثبان فوق الساحل.",
      },
      {
        nameEn: "Nujuma, A Ritz-Carlton Reserve",
        nameAr: "نجومة، ريزيرف من ريتز كارلتون",
        descriptionEn: "The brand's most exclusive tier, an overwater and beachfront reserve on its own island.",
        descriptionAr: "أرقى تصنيفات العلامة، محمية على الماء والشاطئ في جزيرتها الخاصة.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Reef snorkelling",
        placeAr: "سنوركل في الشعاب",
        descriptionEn: "The water is calmest and clearest before midday.",
        descriptionAr: "المياه في أهدأ وأصفى حالاتها قبل الظهيرة.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Private beach",
        placeAr: "شاطئ خاص",
        descriptionEn: "Watching the sky change colour over your own stretch of sand.",
        descriptionAr: "مشاهدة السماء تتلون فوق شاطئك الخاص.",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "Dinner under the stars",
        placeAr: "عشاء تحت النجوم",
        descriptionEn: "Resort dining with some of the clearest night skies in the Kingdom.",
        descriptionAr: "عشاء في المنتجع تحت واحدة من أصفى سماوات الليل في المملكة.",
      },
    ],
  },
  "saudi-arabia/abha": {
    storyEn: [
      "Abha sits over 2,200 metres up in the Asir Mountains, and it shows: while the rest of the Kingdom bakes, Abha spends its summer in fog and juniper forest, cool enough that Saudis fly here specifically to escape the heat.",
      "The cable car up to As-Soudah, suspended between just two pillars a kilometre apart, is the easiest way to feel that shift. Below, Rijal Almaa's sixty stone palaces have stood for four hundred years, and Abha's own Art Street turns the city centre into an open-air gallery. This is Saudi Arabia's mountain side, not its desert one.",
      "This is a first glimpse of what your time in Abha could hold. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "ترتفع أبها أكثر من 2,200 متر في جبال عسير، وهذا واضح في طبيعتها: بينما تحترق بقية المملكة، تقضي أبها صيفها بين الضباب وغابات العرعر، بجو بارد لدرجة أن كثيرًا من السعوديين يقصدونها خصيصًا هربًا من الحر.",
      "التلفريك الصاعد إلى السودة، المعلق بين ركيزتين فقط تفصل بينهما مسافة كيلومتر، هو أسهل طريقة لتشعر بهذا التحول. وفي الأسفل، تقف قصور رجال ألمع الستون المبنية من الحجر منذ أربعمئة عام، ويحوّل شارع الفن في أبها وسط المدينة إلى معرض مفتوح. هذا هو الوجه الجبلي للسعودية، لا وجهها الصحراوي.",
      "هذه لمحة أولى عمّا يمكن أن تحمله أيامك في أبها. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "This is the desert kingdom. Except here, the clouds sit below you, not above.",
    pullQuoteAr: "هذه مملكة الصحراء. إلا أن الغيوم هنا تحتك، لا فوقك.",
    weather: {
      bestWindow: {
        labelEn: "Peak escape season",
        labelAr: "موسم الهروب من الحر",
        monthsEn: "March – August",
        monthsAr: "مارس – أغسطس",
        tempEn: "15–25°C, mild year-round",
        tempAr: "15–25°م، معتدلة طوال العام",
        noteEn: "Saudi Arabia's cool-weather escape, comfortable even when Riyadh and Jeddah are in the 40s.",
        noteAr: "ملاذ السعودية من الحر، معتدل حتى حين تتجاوز الحرارة 40 درجة في الرياض وجدة.",
      },
      peakHeat: {
        labelEn: "Coolest & mistiest",
        labelAr: "الأبرد والأكثر ضبابًا",
        monthsEn: "December – February",
        monthsAr: "ديسمبر – فبراير",
        tempEn: "10–20°C, can be misty and wet",
        tempAr: "10–20°م، قد تكون ضبابية وممطرة",
        noteEn: "Genuinely cold at night for Saudi standards, and mountain roads can get foggy.",
        noteAr: "باردة فعليًا ليلًا وفق المعايير السعودية، وقد تصبح طرق الجبال ضبابية.",
      },
      tipEn: "Abha runs noticeably cooler than the rest of the Kingdom year-round, many Saudis visit specifically to escape summer heat elsewhere.",
      tipAr: "تكون أبها أكثر برودة بوضوح من بقية المملكة طوال العام، ويزورها كثير من السعوديين خصيصًا هربًا من حر الصيف في أماكن أخرى.",
    },
    attractions: [
      {
        nameEn: "As-Soudah Cable Car",
        nameAr: "تلفريك السودة",
        categoryEn: "Landmark",
        categoryAr: "معلم",
        descriptionEn: "One of the world's few cable cars suspended between just two pillars, rising to 1,600 metres above sea level.",
        descriptionAr: "أحد أندر التلفريكات في العالم المعلقة بين ركيزتين فقط، يرتفع إلى 1,600 متر فوق سطح البحر.",
      },
      {
        nameEn: "Rijal Almaa Heritage Village",
        nameAr: "قرية رجال ألمع التراثية",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Around sixty multi-storey stone palaces, some 400 years old. Note it operates seasonally, mainly through summer.",
        descriptionAr: "نحو ستين قصرًا حجريًا متعدد الطوابق، بعضها عمره 400 عام. يعمل موسميًا، غالبًا خلال الصيف.",
      },
      {
        nameEn: "Abha Art Street",
        nameAr: "شارع الفن في أبها",
        categoryEn: "Culture",
        categoryAr: "ثقافة",
        descriptionEn: "An open-air gallery through the city centre, murals and installations along the walking street.",
        descriptionAr: "معرض فني مفتوح في وسط المدينة، جداريات وأعمال فنية على طول الممشى.",
      },
      {
        nameEn: "Asir National Park",
        nameAr: "منتزه عسير الوطني",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "Juniper forests and mountain trails across the Sarawat range, best hiked in the cooler morning hours.",
        descriptionAr: "غابات عرعر ومسارات جبلية عبر سلسلة السروات، ويُفضَّل التنزه فيها في ساعات الصباح الباردة.",
      },
    ],
    dining: [
      {
        nameEn: "Bab Al Turath",
        nameAr: "باب التراث",
        cuisineEn: "Traditional Aseeri",
        cuisineAr: "أسيري تقليدي",
        descriptionEn: "Traditional Aseeri flavours in a dining room decorated like a historic Aseer home.",
        descriptionAr: "نكهات أسيرية تقليدية في صالة مصممة على طراز بيت أسيري تاريخي.",
      },
      {
        nameEn: "Assalam Palace Revolving Restaurant",
        nameAr: "مطعم قصر السلام الدوار",
        cuisineEn: "International buffet",
        cuisineAr: "بوفيه عالمي",
        descriptionEn: "A slow-turning restaurant on the 10th floor, mountain views from every seat over the course of a meal.",
        descriptionAr: "مطعم دوار ببطء في الطابق العاشر، إطلالات جبلية من كل مقعد خلال الوجبة.",
      },
    ],
    stay: [
      {
        nameEn: "Abha InterContinental",
        nameAr: "إنتركونتيننتال أبها",
        descriptionEn: "The city's most celebrated address, perched above the Asir Mountains with a rooftop restaurant often above the clouds.",
        descriptionAr: "العنوان الأبرز في المدينة، يطل على جبال عسير مع مطعم على السطح غالبًا ما يكون فوق الغيوم.",
      },
      {
        nameEn: "Zahrat Aseer Hotel",
        nameAr: "فندق زهرة عسير",
        descriptionEn: "Traditional Asiri architecture throughout, for a stay with a genuine sense of place.",
        descriptionAr: "عمارة أسيرية تقليدية في كل تفاصيله، لإقامة تحمل إحساسًا أصيلًا بالمكان.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "As-Soudah Cable Car",
        placeAr: "تلفريك السودة",
        descriptionEn: "Rise above the clouds before the mountain mist burns off.",
        descriptionAr: "اصعد فوق الغيوم قبل أن يتلاشى ضباب الجبل.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Rijal Almaa",
        placeAr: "رجال ألمع",
        descriptionEn: "Wander four centuries of stone palaces (seasonal, check dates before you go).",
        descriptionAr: "تجوّل بين قصور حجرية عمرها أربعة قرون (موسمي، تحقق من المواعيد قبل الذهاب).",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "Dinner at Bab Al Turath",
        placeAr: "عشاء في باب التراث",
        descriptionEn: "Traditional Aseeri cooking to close a day spent in the clouds.",
        descriptionAr: "مطبخ أسيري تقليدي يختم يومًا أمضيته بين الغيوم.",
      },
    ],
  },
  "saudi-arabia/taif": {
    storyEn: [
      "Taif sits high enough above the coastal heat that the Ottomans built a summer palace here, and Saudis have been following their lead ever since. It's known across the region simply as the City of Roses, for the thousands of farms that turn the surrounding hills fragrant each spring.",
      "Shubra Palace, built in the early 1900s for the Sharif of Mecca, still anchors the old town. From there, the road climbs toward Al Hada, switchbacks lined with cliffside tea stalls and baboons happy to watch you drink your tea, before a cable car carries you the rest of the way up for canyon views the road can't match.",
      "This is a first look at what a few days in Taif could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "ترتفع الطائف فوق حرارة الساحل بما يكفي لأن يبني العثمانيون قصرًا صيفيًا هنا، وما زال السعوديون يحذون حذوهم منذ ذلك الحين. تُعرف في أنحاء المنطقة ببساطة بمدينة الورد، بفضل آلاف المزارع التي تعطر التلال المحيطة بها كل ربيع.",
      "لا يزال قصر شبرا، الذي بُني في أوائل القرن العشرين للشريف أمير مكة، يشكل محور المدينة القديمة. ومن هناك يصعد الطريق نحو الهدا، بمنعطفاته المحاطة بمقاهي الشاي على حافة الجبل وقردة البابون التي تراقبك وأنت تحتسي شايك، قبل أن يحملك التلفريك بقية الطريق صعودًا لإطلالات على الوادي لا يمنحها الطريق نفسه.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة في الطائف. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "For a few weeks each spring, this mountain city smells like roses instead of desert dust.",
    pullQuoteAr: "لأسابيع قليلة كل ربيع، تفوح هذه المدينة الجبلية برائحة الورد بدل غبار الصحراء.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – April",
        monthsAr: "نوفمبر – أبريل",
        tempEn: "22–30°C, comfortable",
        tempAr: "22–30°م، معتدلة",
        noteEn: "April brings the Rose Festival, when farms across the hills open for tours and distillery demonstrations.",
        noteAr: "يجلب أبريل مهرجان الورد، حين تفتح المزارع في التلال أبوابها للجولات وعروض تقطير الزيت.",
      },
      peakHeat: {
        labelEn: "Hottest months",
        labelAr: "أشد الأشهر حرارة",
        monthsEn: "June – August",
        monthsAr: "يونيو – أغسطس",
        tempEn: "Up to 36°C by day",
        tempAr: "حتى 36°م نهارًا",
        noteEn: "Still cooler than Makkah or Jeddah below, but keep outdoor time to morning or late afternoon.",
        noteAr: "لا تزال أبرد من مكة أو جدة في الأسفل، لكن اجعل وقتك في الخارج صباحًا أو في وقت متأخر من بعد الظهر.",
      },
      tipEn: "Taif's elevation makes it noticeably cooler than the coast year-round, one of the reasons it became a summer retreat in the first place.",
      tipAr: "يجعل ارتفاع الطائف طقسها أبرد بوضوح من الساحل طوال العام، وهذا أحد أسباب تحولها إلى مصيف منذ البداية.",
    },
    attractions: [
      {
        nameEn: "Shubra Palace",
        nameAr: "قصر شبرا",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "An Ottoman-era palace built for the Sharif of Mecca in the early 1900s, now a museum of local heritage.",
        descriptionAr: "قصر من الحقبة العثمانية بُني لشريف مكة في أوائل القرن العشرين، وهو اليوم متحف للتراث المحلي.",
      },
      {
        nameEn: "Al Hada Mountain Road & Cable Car",
        nameAr: "طريق الهدا والتلفريك",
        categoryEn: "Landmark",
        categoryAr: "معلم",
        descriptionEn: "A winding cliffside road up to Al Hada, followed by a cable car with sweeping canyon views.",
        descriptionAr: "طريق متعرج على حافة الجبل يصعد إلى الهدا، يتبعه تلفريك بإطلالات واسعة على الوادي.",
      },
      {
        nameEn: "Taif Rose Farms",
        nameAr: "مزارع ورد الطائف",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "Farms open for tours and rose-oil distillery demonstrations, best visited during the spring harvest.",
        descriptionAr: "مزارع تفتح أبوابها للجولات وعروض تقطير زيت الورد، وأفضل وقت لزيارتها موسم الحصاد الربيعي.",
      },
      {
        nameEn: "Al Kar Tourist Village",
        nameAr: "قرية الكار السياحية",
        categoryEn: "Family",
        categoryAr: "عائلي",
        descriptionEn: "A mountain village with its own cable car and family activities above the valley floor.",
        descriptionAr: "قرية جبلية بتلفريك خاص بها وأنشطة عائلية فوق أرض الوادي.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Taif Marriott Resort & Spa",
        nameAr: "منتجع وسبا ماريوت الطائف",
        descriptionEn: "Modern mountain luxury, large pools and a well-regarded wellness centre.",
        descriptionAr: "فخامة جبلية عصرية، مسابح واسعة ومركز عافية معروف.",
      },
      {
        nameEn: "Le Méridien Al Hada",
        nameAr: "لو ميريديان الهدا",
        descriptionEn: "Directly opposite the Al Hada cable car station, for easy access to the canyon views.",
        descriptionAr: "يقع مباشرة أمام محطة تلفريك الهدا، لسهولة الوصول إلى إطلالات الوادي.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Shubra Palace",
        placeAr: "قصر شبرا",
        descriptionEn: "Wander the Ottoman-era rooms before the day warms up.",
        descriptionAr: "تجوّل في غرف الحقبة العثمانية قبل أن يدفأ النهار.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "A rose farm",
        placeAr: "مزرعة ورد",
        descriptionEn: "A tour and distillery demonstration, if you're visiting in season.",
        descriptionAr: "جولة وعرض تقطير، إن كانت زيارتك في الموسم.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Al Hada Cable Car",
        placeAr: "تلفريك الهدا",
        descriptionEn: "Ride up as the canyon below turns gold.",
        descriptionAr: "اصعد بينما يتحول الوادي أسفلك إلى اللون الذهبي.",
      },
    ],
  },
  "saudi-arabia/al-ahsa": {
    storyEn: [
      "Al-Ahsa is the largest oasis on Earth, over two and a half million date palms rising out of desert that stretches unbroken in every direction. UNESCO recognised the whole thing in 2018, springs, canals, gardens and all.",
      "The oasis isn't the only strange, beautiful thing here. Al-Qarah Mountain has been hollowed by wind into mushroom-shaped caves you can walk straight into, the Al-Qaisariya Souq has been trading since 1822 under the same covered alleys, and Al Asfar Lake sits naturally, unmistakably yellow, ringed by sand dunes on every side.",
      "This is a first glimpse of what your time in Al-Ahsa could hold. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "الأحساء هي أكبر واحة في العالم، أكثر من مليونين ونصف مليون نخلة ترتفع من صحراء تمتد بلا انقطاع في كل اتجاه. سجّلت اليونسكو الواحة بأكملها عام 2018، بينابيعها وقنواتها وحدائقها.",
      "والواحة ليست الشيء الغريب والجميل الوحيد هنا. جبل القارة نحتته الرياح إلى كهوف بأشكال أشبه بالفطر يمكنك المشي داخلها مباشرة، وسوق القيصرية يتاجر منذ عام 1822 تحت الأزقة المسقوفة ذاتها، وتقع بحيرة الأصفر بلونها الأصفر الطبيعي الواضح، محاطة بالكثبان الرملية من كل جانب.",
      "هذه لمحة أولى عمّا يمكن أن تحمله أيامك في الأحساء. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Surrounded by desert on every side, this remains the largest oasis on Earth, home to a lake that's naturally, unmistakably yellow.",
    pullQuoteAr: "محاطة بالصحراء من كل جانب، لا تزال هذه أكبر واحة على وجه الأرض، وموطن بحيرة صفراء اللون بشكل طبيعي وواضح.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – March",
        monthsAr: "نوفمبر – مارس",
        tempEn: "15–25°C, mild and dry",
        tempAr: "15–25°م، معتدلة وجافة",
        noteEn: "Comfortable for the oasis, Al-Qarah Mountain and the souq; December and January bring local food festivals.",
        noteAr: "مناسبة للواحة وجبل القارة والسوق، وتشهد ديسمبر ويناير مهرجانات طعام محلية.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "April – October",
        monthsAr: "أبريل – أكتوبر",
        tempEn: "42–47°C, intensely hot",
        tempAr: "42–47°م، حر شديد",
        noteEn: "Among the hottest stretches in the Kingdom; save outdoor sites for early morning.",
        noteAr: "من أشد الفترات حرارة في المملكة، فاجعل زيارة المواقع الخارجية في الصباح الباكر.",
      },
      tipEn: "Al-Ahsa's long summer runs six months, plan around November through March if you can.",
      tipAr: "يمتد صيف الأحساء الطويل ستة أشهر، فحاول التخطيط بين نوفمبر ومارس إن أمكن.",
    },
    attractions: [
      {
        nameEn: "Al-Ahsa Oasis",
        nameAr: "واحة الأحساء",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "A UNESCO World Heritage oasis, the largest on Earth, with over two and a half million date palms.",
        descriptionAr: "واحة مسجلة في التراث العالمي لليونسكو، أكبر واحة على وجه الأرض، بأكثر من مليوني ونصف مليون نخلة.",
      },
      {
        nameEn: "Al-Qarah Mountain",
        nameAr: "جبل القارة",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "Wind-carved limestone caves, mushroom-shaped formations and narrow passages you can walk through.",
        descriptionAr: "كهوف من الحجر الجيري نحتتها الرياح، وتكوينات بشكل الفطر وممرات ضيقة يمكنك المشي عبرها.",
      },
      {
        nameEn: "Al-Qaisariya Souq",
        nameAr: "سوق القيصرية",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Trading since 1822, one of the oldest covered markets in the Arabian Peninsula, over 400 shops.",
        descriptionAr: "يتاجر منذ عام 1822، أحد أقدم الأسواق المسقوفة في الجزيرة العربية، ويضم أكثر من 400 محل.",
      },
      {
        nameEn: "Al Asfar Lake",
        nameAr: "بحيرة الأصفر",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "A naturally yellow-tinted lake, coloured by surrounding limestone and sulfur springs, ringed by dunes.",
        descriptionAr: "بحيرة صفراء اللون طبيعيًا، يمنحها لونها الحجر الجيري وينابيع الكبريت المحيطة، وتحيط بها الكثبان الرملية.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Al Ahsa InterContinental",
        nameAr: "إنتركونتيننتال الأحساء",
        descriptionEn: "The region's top-rated address, a comfortable base for the oasis and heritage sites.",
        descriptionAr: "العنوان الأعلى تقييمًا في المنطقة، قاعدة مريحة لزيارة الواحة والمواقع التراثية.",
      },
      {
        nameEn: "Al Ahsa Grand Hotel",
        nameAr: "فندق الأحساء جراند",
        descriptionEn: "A 5-star hotel across from King Faisal University, within walking distance of restaurants.",
        descriptionAr: "فندق خمس نجوم مقابل جامعة الملك فيصل، على مسافة قريبة من المطاعم.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Al-Qarah Mountain",
        placeAr: "جبل القارة",
        descriptionEn: "Walk the wind-carved caves while they're still cool.",
        descriptionAr: "تجوّل في الكهوف المنحوتة بالرياح بينما لا تزال باردة.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Al-Qaisariya Souq",
        placeAr: "سوق القيصرية",
        descriptionEn: "Two centuries of trading history under the same covered alleys.",
        descriptionAr: "قرنان من التاريخ التجاري تحت الأزقة المسقوفة ذاتها.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Al Asfar Lake",
        placeAr: "بحيرة الأصفر",
        descriptionEn: "Watch the light change over yellow water ringed by dunes.",
        descriptionAr: "شاهد الضوء يتغير فوق المياه الصفراء المحاطة بالكثبان.",
      },
    ],
  },
  "saudi-arabia/jazan": {
    storyEn: [
      "Jazan doesn't look like the Saudi Arabia most people picture. It's the Kingdom's tropical corner, humid and green in places, closer to the Horn of Africa than to Riyadh, with a character shaped as much by the sea and the mountains as by the desert.",
      "The Farasan Islands hold a marine sanctuary where whale sharks and dugongs pass close to shore, and a Pearl Merchants' Neighbourhood of coral-built houses left over from the pearling trade. Inland, the Fayfa Mountains rise into terraced coffee farms, stone staircases carved into slopes steep enough to earn the name Land of Hanging Gardens.",
      "This is a first look at what a few days in Jazan could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "لا تشبه جازان الصورة التي يتخيلها معظم الناس عن السعودية. إنها الركن الاستوائي في المملكة، رطب وأخضر في أماكن منه، وأقرب إلى القرن الأفريقي منه إلى الرياض، بطابع شكّله البحر والجبال بقدر ما شكّلته الصحراء.",
      "تضم جزر فرسان محمية بحرية يمر بالقرب من شواطئها سمك القرش الحوتي وخراف البحر، وحي تجار اللؤلؤ ببيوته المبنية من المرجان المتبقية من زمن تجارة اللؤلؤ. وفي الداخل، ترتفع جبال فيفاء إلى مدرجات قهوة زراعية، سلالم حجرية منحوتة في منحدرات شديدة الانحدار استحقت بها لقب أرض الحدائق المعلقة.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة في جازان. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "This is Saudi Arabia's tropical corner, mangroves and coffee terraces where most people still picture only desert.",
    pullQuoteAr: "هذا هو الركن الاستوائي في السعودية، أشجار مانغروف ومدرجات قهوة حيث لا يزال معظم الناس يتخيلون صحراء فقط.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "October – March",
        monthsAr: "أكتوبر – مارس",
        tempEn: "25–32°C, lower humidity",
        tempAr: "25–32°م، رطوبة أقل",
        noteEn: "Also the best birdwatching season on the Farasan Islands, as migratory species arrive.",
        noteAr: "وهو أيضًا أفضل موسم لمراقبة الطيور في جزر فرسان مع وصول الأنواع المهاجرة.",
      },
      peakHeat: {
        labelEn: "Hot and humid season",
        labelAr: "موسم الحر والرطوبة",
        monthsEn: "June – September",
        monthsAr: "يونيو – سبتمبر",
        tempEn: "Over 40°C with humidity above 80%",
        tempAr: "أكثر من 40°م برطوبة تتجاوز 80%",
        noteEn: "The combination of heat and humidity is intense; midday outdoor time is best avoided.",
        noteAr: "الجمع بين الحرارة والرطوبة شديد الوطأة، ويُفضَّل تجنب الوقت في الخارج ظهرًا.",
      },
      tipEn: "The sea stays warm enough to swim in even during the cooler winter months.",
      tipAr: "يبقى البحر دافئًا بما يكفي للسباحة حتى خلال أشهر الشتاء الأكثر برودة.",
    },
    attractions: [
      {
        nameEn: "Farasan Islands",
        nameAr: "جزر فرسان",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "A marine sanctuary for whale sharks, dugongs and sea turtles, reached by boat from Jazan.",
        descriptionAr: "محمية بحرية لسمك القرش الحوتي وخراف البحر والسلاحف البحرية، يُصل إليها بالقارب من جازان.",
      },
      {
        nameEn: "Fayfa Mountains",
        nameAr: "جبال فيفاء",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "Centuries-old stone terraces climbing steep slopes, still growing coffee, maize and pomegranate.",
        descriptionAr: "مدرجات حجرية عمرها قرون تتسلق منحدرات شديدة الانحدار، ولا تزال تُزرع فيها القهوة والذرة والرمان.",
      },
      {
        nameEn: "Pearl Merchants' Neighbourhood",
        nameAr: "حي تجار اللؤلؤ",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Coral-built houses on Farasan with carved plasterwork, left over from the pearling era.",
        descriptionAr: "بيوت مبنية من المرجان في فرسان بزخارف جصية منحوتة، متبقية من زمن تجارة اللؤلؤ.",
      },
      {
        nameEn: "Jazan Corniche",
        nameAr: "كورنيش جازان",
        categoryEn: "Waterfront",
        categoryAr: "واجهة بحرية",
        descriptionEn: "The mainland's waterfront promenade, a relaxed base between island and mountain trips.",
        descriptionAr: "ممشى الواجهة البحرية في البر الرئيسي، قاعدة هادئة بين رحلات الجزر والجبال.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Novotel Jazan",
        nameAr: "نوفوتيل جازان",
        descriptionEn: "A well-located mainland base on the Corniche, praised for its dining and easy access.",
        descriptionAr: "قاعدة جيدة الموقع في البر الرئيسي على الكورنيش، تحظى بتقدير لمطاعمها وسهولة الوصول إليها.",
      },
      {
        nameEn: "Farasan Coral Resort",
        nameAr: "منتجع فرسان كورال",
        descriptionEn: "A stay on the islands themselves, for travellers building their days around the marine sanctuary.",
        descriptionAr: "إقامة في الجزر نفسها، للمسافرين الذين يبنون أيامهم حول المحمية البحرية.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Boat to Farasan",
        placeAr: "قارب إلى فرسان",
        descriptionEn: "Cross to the islands while the water is calmest.",
        descriptionAr: "اعبر إلى الجزر بينما المياه في أهدأ حالاتها.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Pearl Merchants' Neighbourhood",
        placeAr: "حي تجار اللؤلؤ",
        descriptionEn: "Wander the coral houses left over from the pearling trade.",
        descriptionAr: "تجوّل بين بيوت المرجان المتبقية من زمن تجارة اللؤلؤ.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Jazan Corniche",
        placeAr: "كورنيش جازان",
        descriptionEn: "Back on the mainland as the sky colours over the water.",
        descriptionAr: "عودة إلى البر الرئيسي بينما تتلون السماء فوق الماء.",
      },
    ],
  },
  "saudi-arabia/al-jouf": {
    storyEn: [
      "Al-Jouf sits at the far north of the Kingdom, closer to Jordan than to Riyadh, a crossroads oasis that ancient trade caravans depended on long before it became one of the world's largest olive-growing regions.",
      "Marid Castle has stood in Dumat Al-Jandal since roughly the first century, one of the oldest fortresses in Saudi Arabia, with a stone stair you can still climb for a view over the old town at golden hour. Nearby, Zabal Castle and the Sisra Well trace Sakaka's own Nabataean roots, and the mysterious standing stones at Rajajil predate all of it.",
      "This is a first look at what a few days in Al-Jouf could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "تقع الجوف في أقصى شمال المملكة، أقرب إلى الأردن منها إلى الرياض، واحة ملتقى طرق اعتمدت عليها قوافل التجارة القديمة قبل أن تصبح واحدة من أكبر مناطق زراعة الزيتون في العالم.",
      "لا يزال قصر مارد قائمًا في دومة الجندل منذ نحو القرن الأول الميلادي، أحد أقدم الحصون في السعودية، بسلم حجري لا يزال يمكن تسلقه لرؤية البلدة القديمة عند الغروب. وبالقرب منه، يتتبع قصر زعبل وبئر سيسرا جذور سكاكا النبطية، بينما تسبقهما جميعًا أحجار رجاجيل الغامضة المنتصبة.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة في الجوف. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Marid Castle has been standing since roughly the first century. Most visitors to Saudi Arabia have never heard of it.",
    pullQuoteAr: "لا يزال قصر مارد قائمًا منذ نحو القرن الأول الميلادي. ومع ذلك، لم يسمع به معظم زوار السعودية.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "October – March",
        monthsAr: "أكتوبر – مارس",
        tempEn: "18–28°C, mild",
        tempAr: "18–28°م، معتدلة",
        noteEn: "Comfortable for climbing Marid Castle and walking Sakaka's old sites.",
        noteAr: "مناسبة لتسلق قصر مارد والتجول في مواقع سكاكا القديمة.",
      },
      peakHeat: {
        labelEn: "Hot season",
        labelAr: "الموسم الحار",
        monthsEn: "May – September",
        monthsAr: "مايو – سبتمبر",
        tempEn: "Regularly over 40°C",
        tempAr: "غالبًا فوق 40°م",
        noteEn: "Almost all visiting here happens in the cooler months.",
        noteAr: "تتم معظم الزيارات هنا في الأشهر الأكثر برودة.",
      },
      tipEn: "Al-Jouf sees far fewer visitors than Saudi Arabia's better-known destinations, most sites are quiet even in season.",
      tipAr: "تستقبل الجوف زوارًا أقل بكثير من وجهات السعودية الأشهر، ومعظم المواقع هادئة حتى في الموسم.",
    },
    attractions: [
      {
        nameEn: "Marid Castle",
        nameAr: "قصر مارد",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "One of the oldest fortresses in Saudi Arabia, dating to roughly the first century, with a climbable stone stair over Dumat Al-Jandal.",
        descriptionAr: "أحد أقدم الحصون في السعودية، يعود إلى نحو القرن الأول الميلادي، بسلم حجري يمكن تسلقه فوق دومة الجندل.",
      },
      {
        nameEn: "Dumat Al-Jandal",
        nameAr: "دومة الجندل",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "An old town of antiquities including the Mosque of Omar, plus a lake for sailing and jet skiing.",
        descriptionAr: "بلدة قديمة تضم آثارًا من بينها مسجد عمر، إضافة إلى بحيرة للإبحار والدراجات المائية.",
      },
      {
        nameEn: "Zabal Castle & Sisra Well",
        nameAr: "قصر زعبل وبئر سيسرا",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "A hilltop fortress with Nabataean-era foundations, beside a rock-cut well of the same age.",
        descriptionAr: "حصن فوق تلة بأسس من الحقبة النبطية، إلى جانب بئر منحوتة في الصخر من العصر نفسه.",
      },
      {
        nameEn: "Rajajil Columns",
        nameAr: "أعمدة رجاجيل",
        categoryEn: "Ancient",
        categoryAr: "أثري",
        descriptionEn: "Standing stone columns from prehistory, among the oldest man-made structures in the Arabian Peninsula.",
        descriptionAr: "أعمدة حجرية منتصبة من عصور ما قبل التاريخ، من بين أقدم المنشآت البشرية في الجزيرة العربية.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Olive Land Hotel",
        nameAr: "فندق أوليف لاند",
        descriptionEn: "A comfortable base named for the region's other claim to fame, its olive harvest.",
        descriptionAr: "قاعدة إقامة مريحة سُميت تيمنًا بشهرة المنطقة الأخرى، حصاد الزيتون.",
      },
      {
        nameEn: "Raoum Inn Sakaka",
        nameAr: "نزل رعوم سكاكا",
        descriptionEn: "A practical, well-reviewed stay in Sakaka, close to the old sites.",
        descriptionAr: "إقامة عملية وذات تقييمات جيدة في سكاكا، قريبة من المواقع القديمة.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Marid Castle",
        placeAr: "قصر مارد",
        descriptionEn: "Climb the stone stair before the day warms up.",
        descriptionAr: "تسلّق السلم الحجري قبل أن يدفأ النهار.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Dumat Al-Jandal",
        placeAr: "دومة الجندل",
        descriptionEn: "The Mosque of Omar and a walk along the lake.",
        descriptionAr: "مسجد عمر ونزهة على ضفاف البحيرة.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "Zabal Castle",
        placeAr: "قصر زعبل",
        descriptionEn: "A hilltop view over Sakaka as the light turns gold.",
        descriptionAr: "إطلالة من فوق التلة على سكاكا بينما يتحول الضوء إلى الذهبي.",
      },
    ],
  },
  "saudi-arabia/dammam": {
    storyEn: [
      "Dammam and Al Khobar grew rich on oil, and it shows in a way that's more interesting than it sounds: Saudi Aramco used part of that wealth to build Ithra, one of the Gulf's most ambitious cultural centres, drawing over a million visitors in its first few years alone.",
      "The rest of the Eastern Province rhythm is easier-going. Corniches run along both cities for evening walks, Half Moon Bay offers a quieter stretch of coast, and the King Fahd Causeway carries you to Bahrain in under half an hour if you want to make it a two-country trip.",
      "This is a first look at what a few days in Dammam and Al Khobar could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "نمت الدمام والخبر بثراء النفط، ويظهر ذلك بطريقة أكثر إثارة للاهتمام مما يبدو: استخدمت أرامكو السعودية جزءًا من تلك الثروة لبناء إثراء، أحد أكثر المراكز الثقافية طموحًا في الخليج، الذي استقطب أكثر من مليون زائر في سنواته الأولى وحدها.",
      "أما بقية إيقاع المنطقة الشرقية فأكثر هدوءًا. تمتد الكورنيشات على طول المدينتين لنزهات المساء، ويقدم خليج نصف القمر امتدادًا ساحليًا أكثر هدوءًا، ويحملك جسر الملك فهد إلى البحرين في أقل من نصف ساعة إن أردت جعلها رحلة إلى بلدين.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة في الدمام والخبر. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Aramco built the region's oil wealth here, then used part of it to build one of the Gulf's most ambitious cultural centres.",
    pullQuoteAr: "بنت أرامكو ثروة النفط في هذه المنطقة، ثم استخدمت جزءًا منها لبناء أحد أكثر المراكز الثقافية طموحًا في الخليج.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – March",
        monthsAr: "نوفمبر – مارس",
        tempEn: "18–27°C, comfortable",
        tempAr: "18–27°م، معتدلة",
        noteEn: "Ideal for the Corniches, Half Moon Bay and walking between Ithra's galleries.",
        noteAr: "مثالية للكورنيشات وخليج نصف القمر والتجول بين معارض إثراء.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – September",
        monthsAr: "يونيو – سبتمبر",
        tempEn: "Over 45°C with high humidity",
        tempAr: "أكثر من 45°م برطوبة عالية",
        noteEn: "Gulf humidity makes outdoor time genuinely uncomfortable; lean on indoor attractions.",
        noteAr: "رطوبة الخليج تجعل الوقت في الخارج غير مريح فعليًا، فاعتمد على الأماكن المغلقة.",
      },
      tipEn: "Ithra's galleries are fully air-conditioned, a good anchor for a visit at any time of year.",
      tipAr: "معارض إثراء مكيفة بالكامل، وهي محطة جيدة للزيارة في أي وقت من السنة.",
    },
    attractions: [
      {
        nameEn: "Ithra",
        nameAr: "إثراء",
        categoryEn: "Culture",
        categoryAr: "ثقافة",
        descriptionEn: "The King Abdulaziz Center for World Culture in Dhahran, museum galleries, a children's museum and an energy exhibition under one roof.",
        descriptionAr: "مركز الملك عبدالعزيز الثقافي العالمي في الظهران، يضم معارض متحفية ومتحفًا للأطفال ومعرضًا للطاقة تحت سقف واحد.",
      },
      {
        nameEn: "Half Moon Bay",
        nameAr: "خليج نصف القمر",
        categoryEn: "Waterfront",
        categoryAr: "واجهة بحرية",
        descriptionEn: "A quieter stretch of Gulf coastline for a relaxed beach afternoon.",
        descriptionAr: "امتداد ساحلي أكثر هدوءًا على الخليج لظهيرة شاطئية مريحة.",
      },
      {
        nameEn: "Dammam & Khobar Corniches",
        nameAr: "كورنيش الدمام والخبر",
        categoryEn: "Waterfront",
        categoryAr: "واجهة بحرية",
        descriptionEn: "Waterfront promenades through both cities, popular for evening walks.",
        descriptionAr: "ممشيات بحرية عبر المدينتين، مفضلة لنزهات المساء.",
      },
      {
        nameEn: "King Fahd Causeway",
        nameAr: "جسر الملك فهد",
        categoryEn: "Landmark",
        categoryAr: "معلم",
        descriptionEn: "A 25-kilometre bridge to Bahrain, easy to combine with a Dammam trip.",
        descriptionAr: "جسر يمتد 25 كيلومترًا إلى البحرين، يسهل الجمع بينه وبين رحلة إلى الدمام.",
      },
    ],
    dining: [
      {
        nameEn: "Nozomi Khobar",
        nameAr: "نوزومي الخبر",
        cuisineEn: "Japanese",
        cuisineAr: "ياباني",
        descriptionEn: "Award-winning Japanese dining on the Corniche, with sea views to match.",
        descriptionAr: "مطبخ ياباني حائز على جوائز على الكورنيش، بإطلالات بحرية تليق به.",
      },
      {
        nameEn: "Maharaja by Vineet",
        nameAr: "مهراجا باي فينيت",
        cuisineEn: "Indian",
        cuisineAr: "هندي",
        descriptionEn: "Michelin-starred chef Vineet Bhatia's Indian restaurant inside the Mövenpick Hotel.",
        descriptionAr: "مطعم هندي للشيف الحائز على نجمة ميشلان فينيت بهاتيا، داخل فندق موفنبيك.",
      },
      {
        nameEn: "The Butcher Shop & Grill",
        nameAr: "ذا بوتشر شوب آند غريل",
        cuisineEn: "Steakhouse",
        cuisineAr: "ستيك هاوس",
        descriptionEn: "A South African steakhouse chain known for premium cuts and ribs.",
        descriptionAr: "سلسلة مطاعم ستيك هاوس جنوب أفريقية معروفة بقطعها الفاخرة وأضلاعها.",
      },
      {
        nameEn: "Stefano's Italian Kitchen",
        nameAr: "ستيفانو إيطاليان كيتشن",
        cuisineEn: "Italian",
        cuisineAr: "إيطالي",
        descriptionEn: "A reliable, well-regarded address for Italian cooking in Al Khobar.",
        descriptionAr: "عنوان موثوق ومحبوب للمطبخ الإيطالي في الخبر.",
      },
    ],
    stay: [
      {
        nameEn: "Kempinski Al Othman Hotel Al Khobar",
        nameAr: "فندق كمبينسكي العثمان الخبر",
        descriptionEn: "The region's premium address, tailored for a polished business or leisure stay.",
        descriptionAr: "العنوان الفاخر في المنطقة، مصمم لإقامة أنيقة سواء للعمل أو الترفيه.",
      },
      {
        nameEn: "Le Méridien Al Khobar",
        nameAr: "لو ميريديان الخبر",
        descriptionEn: "Gulf views from the waterfront, with an outdoor pool, tennis courts and a full spa.",
        descriptionAr: "إطلالات على الخليج من الواجهة البحرية، مع مسبح خارجي وملاعب تنس وسبا متكامل.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Ithra",
        placeAr: "إثراء",
        descriptionEn: "A slow morning through the galleries in Dhahran.",
        descriptionAr: "صباح هادئ بين المعارض في الظهران.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Half Moon Bay",
        placeAr: "خليج نصف القمر",
        descriptionEn: "A quieter stretch of coast for the warmest hours.",
        descriptionAr: "امتداد ساحلي أكثر هدوءًا لساعات الحر الشديد.",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "Dinner at Nozomi Khobar",
        placeAr: "عشاء في نوزومي الخبر",
        descriptionEn: "Japanese cooking and sea views to close the day on the Corniche.",
        descriptionAr: "مطبخ ياباني وإطلالات بحرية تختم اليوم على الكورنيش.",
      },
    ],
  },
  "saudi-arabia/tabuk": {
    storyEn: [
      "Tabuk has always been a frontier. Nabataean traders carved tombs and inscriptions into the cliffs at Magna two thousand years ago, and the Ottomans built a fortress in the city centre tied to the Prophet Muhammad's own expedition here in 630 CE.",
      "Now it's a frontier again. NEOM is rising along the coast an hour or so away, while inland, Wadi Al Disah, often called Saudi Arabia's Grand Canyon, cuts fifteen kilometres through red cliffs that rise 500 metres above spring-fed palm groves. Old and new sit closer together here than almost anywhere else in the Kingdom.",
      "This is a first look at what a few days in Tabuk could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "كانت تبوك دائمًا منطقة حدودية. نحت التجار الأنباط مقابر ونقوشًا في منحدرات مقنا قبل ألفي عام، وبنى العثمانيون حصنًا في وسط المدينة مرتبطًا بغزوة النبي محمد صلى الله عليه وسلم عام 630 ميلادي.",
      "واليوم أصبحت منطقة حدودية من جديد. ترتفع نيوم على الساحل على بعد نحو ساعة من هنا، بينما يشق وادي الديسة في الداخل، الذي يُلقب غالبًا بجراند كانيون السعودية، مسافة خمسة عشر كيلومترًا عبر منحدرات حمراء ترتفع 500 متر فوق واحات نخيل تغذيها الينابيع. يلتقي القديم بالجديد هنا بقرب لا تجده في أي مكان آخر في المملكة تقريبًا.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة في تبوك. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "The carvings at Magna are two thousand years old. NEOM, an hour up the coast, is being built from scratch this decade.",
    pullQuoteAr: "نقوش مقنا عمرها ألفا عام. وعلى بعد ساعة على الساحل، تُبنى نيوم من الصفر في هذا العقد.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "October – April",
        monthsAr: "أكتوبر – أبريل",
        tempEn: "10–25°C, cool and pleasant",
        tempAr: "10–25°م، باردة ولطيفة",
        noteEn: "Among the coolest of Saudi Arabia's desert regions, ideal for Wadi Al Disah and Tabuk Castle.",
        noteAr: "من أبرد المناطق الصحراوية في السعودية، مثالية لوادي الديسة وقلعة تبوك.",
      },
      peakHeat: {
        labelEn: "Hot season",
        labelAr: "الموسم الحار",
        monthsEn: "June – August",
        monthsAr: "يونيو – أغسطس",
        tempEn: "Up to 40°C",
        tempAr: "حتى 40°م",
        noteEn: "Still more manageable than much of the Kingdom, but outdoor sites are best kept to morning hours.",
        noteAr: "لا تزال أكثر احتمالًا من معظم أنحاء المملكة، لكن يُفضَّل زيارة المواقع الخارجية صباحًا.",
      },
      tipEn: "Tabuk's northern latitude and elevation make it noticeably cooler than the rest of Saudi Arabia year-round.",
      tipAr: "يجعل موقع تبوك الشمالي وارتفاعها طقسها أبرد بوضوح من بقية السعودية طوال العام.",
    },
    attractions: [
      {
        nameEn: "Wadi Al Disah",
        nameAr: "وادي الديسة",
        categoryEn: "Nature",
        categoryAr: "طبيعة",
        descriptionEn: "A 15-kilometre canyon of red cliffs up to 500 metres high, spring-fed palm groves and Nabataean tomb facades, often called Saudi Arabia's Grand Canyon.",
        descriptionAr: "وادٍ بطول 15 كيلومترًا بمنحدرات حمراء يصل ارتفاعها إلى 500 متر، وواحات نخيل تغذيها الينابيع وواجهات مقابر نبطية، ويُلقب غالبًا بجراند كانيون السعودية.",
      },
      {
        nameEn: "Tabuk Castle",
        nameAr: "قلعة تبوك",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "A restored Ottoman-era fortress in the city centre, tied to the Prophet Muhammad's expedition to Tabuk.",
        descriptionAr: "حصن عثماني مرمم في وسط المدينة، مرتبط بغزوة النبي محمد صلى الله عليه وسلم إلى تبوك.",
      },
      {
        nameEn: "Magna",
        nameAr: "مقنا",
        categoryEn: "Ancient",
        categoryAr: "أثري",
        descriptionEn: "An ancient site near the Red Sea with Nabataean rock inscriptions, wells and cliff-face carvings.",
        descriptionAr: "موقع أثري قرب البحر الأحمر يضم نقوشًا صخرية نبطية وآبارًا ونحتًا على واجهات الجبال.",
      },
      {
        nameEn: "Tabuk's Red Sea coast",
        nameAr: "ساحل تبوك على البحر الأحمر",
        categoryEn: "Coast",
        categoryAr: "ساحل",
        descriptionEn: "Clear water and quiet beaches along the province's stretch of coastline.",
        descriptionAr: "مياه صافية وشواطئ هادئة على طول امتداد المنطقة الساحلي.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Hilton Garden Inn Tabuk",
        nameAr: "هيلتون غاردن إن تبوك",
        descriptionEn: "A dependable base with an indoor pool and 24-hour gym.",
        descriptionAr: "قاعدة إقامة موثوقة بمسبح داخلي وصالة رياضية على مدار الساعة.",
      },
      {
        nameEn: "Holiday Inn Tabuk",
        nameAr: "هوليداي إن تبوك",
        descriptionEn: "A comfortable, family-friendly stay convenient for trips toward NEOM.",
        descriptionAr: "إقامة مريحة وملائمة للعائلات، وموقع عملي للرحلات نحو نيوم.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Wadi Al Disah",
        placeAr: "وادي الديسة",
        descriptionEn: "Walk the canyon floor while it's still cool.",
        descriptionAr: "امشِ في قاع الوادي بينما لا يزال باردًا.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Tabuk Castle",
        placeAr: "قلعة تبوك",
        descriptionEn: "A restored fortress with centuries of history in the city centre.",
        descriptionAr: "حصن مرمم يحمل قرونًا من التاريخ في وسط المدينة.",
      },
      {
        timeEn: "Sunset",
        timeAr: "الغروب",
        placeEn: "The coast road",
        placeAr: "طريق الساحل",
        descriptionEn: "A drive toward the Red Sea as the light softens.",
        descriptionAr: "رحلة بالسيارة نحو البحر الأحمر بينما يخفت الضوء.",
      },
    ],
  },
  "saudi-arabia/yanbu": {
    storyEn: [
      "Yanbu is what Jeddah might feel like with a fraction of the crowds. The same Red Sea, the same Hejazi coral-block architecture in its old town, and reefs that have barely been dived thanks to decades spent out of the spotlight.",
      "T. E. Lawrence, of Lawrence of Arabia, once lived in a house that still stands in the historic quarter, a few minutes' walk from a souq and a waterfront that stretches 11 kilometres along the coast. It's a smaller, quieter version of everything people come to the Red Sea for.",
      "This is a first look at what a few days in Yanbu could feel like. Tell us your dates and who's travelling, and we'll shape the rest around you.",
    ],
    storyAr: [
      "ينبع هي ما قد تشعر به جدة لو كانت بجزء بسيط من زحامها. البحر الأحمر ذاته، والعمارة الحجازية ذاتها المبنية بالحجر المرجاني في مدينتها القديمة، وشعاب مرجانية لم تُغَص إلا نادرًا بفضل عقود قضتها بعيدًا عن الأضواء.",
      "عاش تي. إي. لورنس، المعروف بلورانس العرب، في بيت لا يزال قائمًا في الحي التاريخي، على بعد دقائق من سوق وواجهة بحرية تمتد 11 كيلومترًا على طول الساحل. إنها نسخة أصغر وأكثر هدوءًا من كل ما يقصد الناس البحر الأحمر من أجله.",
      "هذه لمحة أولى عمّا يمكن أن تشعر به أيام قليلة في ينبع. أخبرنا بتواريخك ومن سيرافقك، وسنشكّل الباقي حولك.",
    ],
    pullQuoteEn: "Lawrence of Arabia once lived in this old town. The reefs a few minutes offshore have barely been dived since.",
    pullQuoteAr: "عاش لورانس العرب يومًا في هذه المدينة القديمة. أما الشعاب المرجانية على بعد دقائق من الشاطئ فلم تُغَص تقريبًا منذ ذلك الحين.",
    weather: {
      bestWindow: {
        labelEn: "Best time to visit",
        labelAr: "أفضل وقت للزيارة",
        monthsEn: "November – March",
        monthsAr: "نوفمبر – مارس",
        tempEn: "22–25°C, mild",
        tempAr: "22–25°م، معتدلة",
        noteEn: "Also the best window for diving, clear water and pleasant conditions offshore.",
        noteAr: "وهي أيضًا أفضل فترة للغوص، بمياه صافية وأجواء لطيفة قبالة الساحل.",
      },
      peakHeat: {
        labelEn: "Peak summer heat",
        labelAr: "ذروة الحر الصيفي",
        monthsEn: "June – September",
        monthsAr: "يونيو – سبتمبر",
        tempEn: "Around 39°C, hot and humid",
        tempAr: "نحو 39°م، حار ورطب",
        noteEn: "Coastal humidity makes midday outdoor time uncomfortable; evenings on the Corniche stay pleasant.",
        noteAr: "الرطوبة الساحلية تجعل وقت الظهيرة في الخارج غير مريح، لكن أمسيات الكورنيش تبقى لطيفة.",
      },
      tipEn: "Diving conditions are best from October through April, when the water is clearest.",
      tipAr: "ظروف الغوص في أفضل حالاتها من أكتوبر إلى أبريل، حين تكون المياه في أصفى حالاتها.",
    },
    attractions: [
      {
        nameEn: "Yanbu Historic Old Town",
        nameAr: "ينبع التاريخية",
        categoryEn: "Heritage",
        categoryAr: "تراث",
        descriptionEn: "Coral-block Hejazi architecture, a souq and the house where T. E. Lawrence once lived.",
        descriptionAr: "عمارة حجازية من الحجر المرجاني، وسوق، والبيت الذي عاش فيه تي. إي. لورنس.",
      },
      {
        nameEn: "Yanbu Corniche",
        nameAr: "كورنيش ينبع",
        categoryEn: "Waterfront",
        categoryAr: "واجهة بحرية",
        descriptionEn: "An 11-kilometre waterfront promenade with parks and restaurants along the Red Sea.",
        descriptionAr: "ممشى بحري يمتد 11 كيلومترًا بحدائق ومطاعم على طول البحر الأحمر.",
      },
      {
        nameEn: "Barracuda Beach",
        nameAr: "شاطئ باراكودا",
        categoryEn: "Diving",
        categoryAr: "غوص",
        descriptionEn: "Coral formations beginning close to shore, a favourite for snorkelling.",
        descriptionAr: "تكوينات مرجانية تبدأ قريبًا من الشاطئ، مفضلة لهواة السنوركل.",
      },
      {
        nameEn: "Al-Farabi Coral Reef",
        nameAr: "شعاب الفارابي المرجانية",
        categoryEn: "Diving",
        categoryAr: "غوص",
        descriptionEn: "A vibrant, uncrowded dive site rarely visited by international tourists.",
        descriptionAr: "موقع غوص نابض بالحياة وغير مزدحم، نادرًا ما يزوره السياح الدوليون.",
      },
    ],
    dining: [],
    stay: [
      {
        nameEn: "Novotel Yanbu",
        nameAr: "نوفوتيل ينبع",
        descriptionEn: "A full-service spa with steam room and sauna, a comfortable modern base.",
        descriptionAr: "سبا متكامل بغرفة بخار وساونا، قاعدة إقامة عصرية ومريحة.",
      },
      {
        nameEn: "Canary Beach Hotel",
        nameAr: "فندق كناري بيتش",
        descriptionEn: "An à la carte restaurant and fitness centre, close to the waterfront.",
        descriptionAr: "مطعم بقائمة طعام مفتوحة ومركز لياقة، قريب من الواجهة البحرية.",
      },
    ],
    sampleDay: [
      {
        timeEn: "Morning",
        timeAr: "الصباح",
        placeEn: "Yanbu Old Town",
        placeAr: "ينبع القديمة",
        descriptionEn: "Coral-block lanes and Lawrence's old house before the heat builds.",
        descriptionAr: "أزقة الحجر المرجاني وبيت لورنس القديم قبل اشتداد الحر.",
      },
      {
        timeEn: "Afternoon",
        timeAr: "بعد الظهر",
        placeEn: "Barracuda Beach",
        placeAr: "شاطئ باراكودا",
        descriptionEn: "Snorkelling reefs that start just off the sand.",
        descriptionAr: "شعاب سنوركل تبدأ فور الوصول إلى الرمال.",
      },
      {
        timeEn: "Evening",
        timeAr: "المساء",
        placeEn: "Yanbu Corniche",
        placeAr: "كورنيش ينبع",
        descriptionEn: "An evening stroll and a fish dinner by the water.",
        descriptionAr: "نزهة مسائية وعشاء سمك على الماء.",
      },
    ],
  },
};

export const flagshipCityGuideBySlug = (countrySlug: string, citySlug: string) =>
  flagshipCityGuides[`${countrySlug}/${citySlug}`];
