import type { LegalSection } from "./components/legal-page";

export const legalUpdatedEn = "24 August 2026";
export const legalUpdatedAr = "24 أغسطس 2026";

export const privacyEn: LegalSection[] = [
  { id: "who-we-are", title: "Who we are", paragraphs: ["This notice explains how MEMORIES Travel (\"MEMORIES\", \"we\", \"us\") handles personal data through memories.tours, our journey-request forms, the AI concierge on the site, email, WhatsApp and related customer-support channels. MEMORIES is based in Riyadh, Saudi Arabia. Our privacy contact is memoriesksasupport@gmail.com."] },
  { id: "data-we-collect", title: "Information we collect", bullets: ["Identity and contact data, such as your name, email address, telephone number, country code and preferred contact channel.", "Journey information, including destination, dates, traveller type and count, budget, transport, accommodation, experiences, study-abroad needs and any notes you choose to provide.", "Information about companions that you provide. You must have permission to share their information, and please avoid passport, health or other sensitive details unless we specifically ask for them through a secure channel.", "Messages you send to the AI concierge on the site, and anything you write on our feedback page. Feedback needs no name or email unless you want a reply.", "Technical data needed to operate and secure the website, such as IP address, browser and device information, server logs and essential local-storage preferences.", "Marketing preference and newsletter email address, only when you separately choose to subscribe."] },
  { id: "why-we-use", title: "Why we use your information", paragraphs: ["We use your journey information to research and write your travel plan, to answer you, to provide customer service, to prevent misuse, to maintain business records and to comply with legal obligations. Sending a request authorizes service communications about that request; it does not subscribe you to marketing.", "Where required, we rely on your consent for optional marketing, and you can withdraw it at any time. We do not sell personal data."] },
  { id: "ai", title: "How AI is used, and what it sees", paragraphs: ["Your travel plan is drafted by an AI system before a person on our team reviews it. To do that, the details you gave us in the form, including your name, dates, traveller count, budget and any notes you wrote, are sent to our AI provider, Anthropic, which processes them to generate the draft. Messages you send to the concierge on the site are sent to the same provider to generate its replies.", "This is processing on our instructions for the purpose you asked for. Your information is not used by us or by that provider to train AI models. If you would prefer your request not be handled this way, tell us at memoriesksasupport@gmail.com and we will arrange it manually instead.", "A plan is never sent to you on the AI\u2019s say-so alone. A person reviews it first, and the plan itself flags what still needs confirming."] },
  { id: "sharing", title: "Who we share it with", paragraphs: ["We use a small number of service providers to run the site and produce your plan. Each receives only what it needs, and none of them may use your information for their own purposes."], bullets: ["Vercel, which hosts the website and serves the pages.", "Supabase, which stores your request and your plan in our database.", "Anthropic, which processes your request to draft your plan and to power the concierge, as described above.", "Resend, which delivers our emails to you.", "Government, immigration, law-enforcement or regulatory bodies when legally required.", "Professional advisers and technology or security providers bound by appropriate duties.", "A successor organization in a lawful merger, acquisition or restructuring, subject to applicable safeguards."] },
  { id: "not-shared", title: "Who we do not share it with", paragraphs: ["We do not book travel for you, so we do not pass your details to airlines, hotels, drivers, tour operators or activity providers. When you book, you deal with them yourself and give them your own details on their own terms.", "We take no payment for travel and hold no card details for it. The only payment we take is our own planning fee."] },
  { id: "international", title: "International transfers", paragraphs: ["Our hosting, database, email and AI providers may process data outside Saudi Arabia. Where personal data is transferred internationally, we use the mechanisms and safeguards required by applicable Saudi data-protection law and limit the transfer to what is necessary for the stated purpose."] },
  { id: "retention", title: "How long we keep it", paragraphs: ["Requests that do not become a plan are ordinarily kept for up to 24 months after the last meaningful contact, then deleted or anonymized, unless a longer period is needed for a complaint, a legal claim, fraud prevention or the law.", "A plan you have paid for is kept so that your plan link keeps working and so we have a record of what we sold you. Payment and tax records are kept for the period the law requires. Marketing contact information is kept until you unsubscribe or ask us to delete it."] },
  { id: "rights", title: "Your choices and rights", paragraphs: ["Subject to applicable law, you may ask to be informed about our processing, access your data, obtain a copy, correct it, request deletion, withdraw consent or object to certain uses. You can unsubscribe using the link in any marketing email or by contacting us. We may verify your identity and may retain limited information where the law requires it. Send requests to memoriesksasupport@gmail.com. You may also raise a complaint with the competent Saudi data-protection authority."] },
  { id: "security", title: "Security and children", paragraphs: ["We use reasonable technical and organizational measures to protect information, but no online service is completely risk-free. Please do not submit passport scans, payment-card details or medical information in free-text fields. Our service is not directed to children acting independently; a parent or legal guardian must submit and manage requests involving minors."] },
  { id: "changes", title: "Changes to this notice", paragraphs: ["We may update this notice when our services, providers or legal obligations change. The date at the top shows the latest version, and material changes will be highlighted where appropriate."] },
];

export const privacyAr: LegalSection[] = [
  { id: "who-we-are", title: "من نحن", paragraphs: ["يوضح هذا الإشعار كيف تتعامل ميموريز للسفر (\"ميموريز\"، \"نحن\") مع البيانات الشخصية عبر موقع memories.tours، ونماذج طلب الرحلات، والمساعد الذكي في الموقع، والبريد الإلكتروني وواتساب وقنوات الدعم. مقر ميموريز في الرياض بالمملكة العربية السعودية، وللتواصل بشأن الخصوصية: memoriesksasupport@gmail.com."] },
  { id: "data-we-collect", title: "المعلومات التي نجمعها", bullets: ["بيانات الهوية والتواصل: الاسم والبريد الإلكتروني ورقم الهاتف ورمز الدولة وقناة التواصل المفضلة.", "معلومات الرحلة: الوجهة والتواريخ ونوع المسافرين وعددهم والميزانية والنقل والإقامة والتجارب واحتياجات الدراسة بالخارج وأي ملاحظات تكتبها.", "معلومات المرافقين التي تزودنا بها. يجب أن يكون لديك إذنهم، ونرجو تجنّب بيانات الجواز أو الصحة أو غيرها من البيانات الحساسة ما لم نطلبها تحديدًا عبر قناة آمنة.", "رسائلك إلى المساعد الذكي في الموقع، وما تكتبه في صفحة الآراء. صفحة الآراء لا تتطلب اسمًا ولا بريدًا إلا إن أردت ردًا.", "بيانات تقنية لتشغيل الموقع وتأمينه: عنوان IP ومعلومات المتصفح والجهاز وسجلات الخادم وتفضيلات التخزين المحلي الأساسية.", "تفضيلات التسويق وبريد النشرة، فقط إذا اخترت الاشتراك بشكل منفصل."] },
  { id: "why-we-use", title: "لماذا نستخدم معلوماتك", paragraphs: ["نستخدم معلومات رحلتك للبحث وكتابة خطة سفرك، وللرد عليك، وتقديم خدمة العملاء، ومنع إساءة الاستخدام، وحفظ السجلات، والامتثال للأنظمة. وإرسال الطلب يخوّلنا مراسلتك بشأنه، ولا يعني اشتراكك في التسويق.", "وعند الحاجة نعتمد على موافقتك للتسويق الاختياري، ويمكنك سحبها في أي وقت. ونحن لا نبيع البيانات الشخصية."] },
  { id: "ai", title: "كيف نستخدم الذكاء الاصطناعي وما الذي يطّلع عليه", paragraphs: ["تُكتب خطة سفرك بواسطة نظام ذكاء اصطناعي، ثم يراجعها شخص من فريقنا قبل وصولها إليك. ولإتمام ذلك تُرسل التفاصيل التي كتبتها في النموذج، ومنها اسمك وتواريخك وعدد المسافرين وميزانيتك وأي ملاحظات، إلى مزودنا للذكاء الاصطناعي وهو Anthropic، الذي يعالجها لإنشاء المسودة. كما تُرسل رسائلك إلى المساعد في الموقع إلى المزود نفسه لتوليد ردوده.", "هذه معالجة تتم بناءً على تعليماتنا وللغرض الذي طلبته أنت. ولا نستخدم معلوماتك، ولا يستخدمها ذلك المزود، لتدريب نماذج الذكاء الاصطناعي. وإن كنت تفضّل ألا يُعالج طلبك بهذه الطريقة، أخبرنا على memoriesksasupport@gmail.com وسنرتّبه يدويًا بدلًا من ذلك.", "ولا تُرسل أي خطة إليك بقرار من الذكاء الاصطناعي وحده، بل يراجعها إنسان أولًا، وتشير الخطة نفسها إلى ما يحتاج إلى تأكيد."] },
  { id: "sharing", title: "مع من نشاركها", paragraphs: ["نستعين بعدد محدود من مزودي الخدمات لتشغيل الموقع وإنتاج خطتك. ويتلقى كل منهم ما يلزمه فقط، ولا يجوز لأي منهم استخدام معلوماتك لأغراضه الخاصة."], bullets: ["Vercel، لاستضافة الموقع وتقديم الصفحات.", "Supabase، لتخزين طلبك وخطتك في قاعدة بياناتنا.", "Anthropic، لمعالجة طلبك وكتابة مسودة خطتك وتشغيل المساعد، كما هو موضح أعلاه.", "Resend، لإيصال رسائل البريد الإلكتروني إليك.", "الجهات الحكومية أو جهات الهجرة أو إنفاذ النظام أو الجهات التنظيمية عند الإلزام النظامي.", "المستشارون المهنيون ومزودو التقنية والأمن الملتزمون بواجبات مناسبة.", "منشأة خَلَف في عملية اندماج أو استحواذ أو إعادة هيكلة مشروعة، مع الضمانات المعمول بها."] },
  { id: "not-shared", title: "مع من لا نشاركها", paragraphs: ["نحن لا نحجز لك السفر، ولذلك لا نمرر بياناتك إلى شركات الطيران أو الفنادق أو السائقين أو منظمي الرحلات أو مزودي الأنشطة. وعندما تحجز أنت، تتعامل معهم مباشرة وتعطيهم بياناتك بنفسك وفق شروطهم.", "ولا نستوفي أي مبالغ مقابل السفر ولا نحتفظ ببيانات بطاقات لأجله. المبلغ الوحيد الذي نستوفيه هو رسوم التخطيط الخاصة بنا."] },
  { id: "international", title: "النقل الدولي للبيانات", paragraphs: ["قد يعالج مزودو الاستضافة وقاعدة البيانات والبريد والذكاء الاصطناعي البيانات خارج المملكة. وعند نقل البيانات الشخصية دوليًا نستخدم الآليات والضمانات التي يتطلبها نظام حماية البيانات الشخصية المعمول به، ونقصر النقل على ما يلزم للغرض المعلن."] },
  { id: "retention", title: "مدة الاحتفاظ", paragraphs: ["الطلبات التي لا تتحول إلى خطة يُحتفظ بها عادة حتى 24 شهرًا من آخر تواصل فعلي، ثم تُحذف أو تُصبح مجهولة الهوية، ما لم تلزم مدة أطول لشكوى أو مطالبة نظامية أو منع احتيال أو التزام نظامي.", "أما الخطة التي دفعت مقابلها فنحتفظ بها ليبقى رابط خطتك يعمل وليكون لدينا سجل بما بعناه لك. وتُحفظ سجلات الدفع والضرائب للمدة التي يتطلبها النظام. وتُحفظ بيانات التسويق حتى تلغي الاشتراك أو تطلب حذفها."] },
  { id: "rights", title: "خياراتك وحقوقك", paragraphs: ["وفقًا للأنظمة المعمول بها، يمكنك طلب العلم بمعالجتنا لبياناتك، والوصول إليها، والحصول على نسخة، وتصحيحها، وطلب إتلافها، وسحب الموافقة، والاعتراض على بعض الاستخدامات. ويمكنك إلغاء الاشتراك عبر الرابط في أي رسالة تسويقية أو بالتواصل معنا. وقد نتحقق من هويتك وقد نحتفظ بمعلومات محدودة متى تطلب النظام ذلك. أرسل طلباتك إلى memoriesksasupport@gmail.com، ولك أيضًا رفع شكوى إلى الجهة المختصة بحماية البيانات في المملكة."] },
  { id: "security", title: "الأمان والأطفال", paragraphs: ["نستخدم تدابير تقنية وتنظيمية معقولة لحماية المعلومات، غير أن أي خدمة عبر الإنترنت لا تخلو من المخاطر تمامًا. نرجو عدم إرسال صور الجوازات أو بيانات البطاقات أو المعلومات الطبية في الحقول النصية المفتوحة. وخدمتنا ليست موجهة للأطفال بشكل مستقل، ويجب أن يقدّم ولي الأمر أو الوصي الطلبات المتعلقة بالقاصرين ويديرها."] },
  { id: "changes", title: "تحديثات هذا الإشعار", paragraphs: ["قد نحدّث هذا الإشعار عند تغير خدماتنا أو مزودينا أو التزاماتنا النظامية. ويوضح التاريخ في الأعلى النسخة الحالية، وسنبرز التغييرات الجوهرية عند الاقتضاء."] },
];

export const termsEn: LegalSection[] = [
  { id: "scope", title: "Scope and acceptance", paragraphs: ["These Terms govern your use of memories.tours and any request you send to MEMORIES. By using the site or submitting a request, you confirm that you can enter a binding agreement and that the information you provide is accurate and lawful."] },
  { id: "what-we-sell", title: "What we sell, and what we do not", paragraphs: ["MEMORIES sells a written travel plan. That is the whole product. We are not a travel agent, a tour operator or a booking platform, and we hold no agency, affiliation or commercial arrangement with any airline, hotel, driver, restaurant or activity provider we name.", "We do not book anything for you, and we never will under these Terms. We do not hold reservations, issue tickets, take deposits on a supplier\u2019s behalf, or act as an intermediary between you and any supplier. Your plan tells you what to book, where to book it and roughly how far ahead. You make every booking yourself, in your own name, directly with the supplier, on that supplier\u2019s own terms and paying that supplier\u2019s own price.", "Nothing we produce is a reservation. Not the plan, not the overview, not a named hotel, not an estimated figure. If you need something held, you must go and hold it yourself."] },
  { id: "the-plan", title: "How your plan is written", paragraphs: ["Your plan is drafted by an AI system from your answers, from research we hold about the destination and from current web research, and it is then read by a person on our team before it reaches you. We take that review seriously, and it is still a document about the real world written in advance.", "Opening hours, prices, seasonal closures, entry rules and visa requirements change, sometimes at short notice and sometimes between our writing and your travelling. Treat your plan as informed guidance to act on, not as a warranty of fact. Confirm anything that matters, especially anything you are about to pay for or that governs whether you can enter a country, with the supplier or the relevant authority before you rely on it."] },
  { id: "fees", title: "Our fee, and the cost of travel", paragraphs: ["Our fee is for the plan and nothing else. It is SAR 15 for each night of the trip plus SAR 20 for each destination after the first, up to a maximum of three destinations, and the planner shows the fee while you fill in the form. Study-abroad plans are quoted by our team after we see the request.", "Every travel figure inside a plan is an estimate to help you budget. It is not a quote, not a price we have secured and not a price anyone has agreed to hold for you. You pay suppliers directly at whatever they charge on the day. We receive no commission from any supplier we name, and naming one is not a recommendation that carries any financial interest for us."] },
  { id: "traveller", title: "Your responsibilities", bullets: ["Give accurate information in the planning form. A plan built on the wrong dates, traveller count or budget will be wrong in ways we cannot see.", "Hold the valid passports, visas, permits, insurance, vaccinations and entry documents the relevant authorities require.", "Check entry rules, health requirements and supplier terms yourself before booking or travelling, whatever your plan says.", "Make and manage your own bookings, and read the terms of each supplier you book with.", "Tell us about accessibility, mobility, dietary or other needs when you request the plan, so the plan can account for them.", "Do not misuse the website, submit unlawful content, attempt unauthorized access or impersonate another person."] },
  { id: "visa", title: "Visas, study and official decisions", paragraphs: ["A plan may explain a visa route, a document list or an application process. That is information, not representation: we do not lodge applications for you and we are not your agent before any authority.", "Visa, immigration, admission, scholarship and border decisions are made solely by the relevant authorities or institutions. We do not guarantee an outcome or a processing time, and we are not responsible for a refusal, a delay, or a rule that changed after your plan was written."] },
  { id: "content", title: "Website content and intellectual property", paragraphs: ["The MEMORIES name, branding, original copy, design and site content are protected by applicable intellectual-property law. Your plan is licensed to you for your own trip: you may keep it, print it and share it with the people travelling with you. You may not resell it, publish it or use it commercially. Third-party names and images remain the property of their owners."] },
  { id: "liability", title: "Liability", paragraphs: ["Nothing in these Terms excludes liability that cannot legally be excluded, and your mandatory rights as a consumer under Saudi law are unaffected.", "Because we book nothing and supply no travel, we are not responsible for what any supplier does or fails to do: a cancelled flight, a hotel that does not honour a reservation, a closed attraction, a driver who does not arrive, an overbooking, a price change or a refusal of entry. Those sit between you and that supplier, or that authority.", "To the extent permitted by law, our liability in connection with a plan is limited to the fee you paid us for that plan, and we are not liable for indirect or consequential loss. That limit does not apply to death or personal injury caused by our negligence, to fraud, or to anything else the law does not permit us to limit."] },
  { id: "law", title: "Law, complaints and changes", paragraphs: ["These Terms are governed by the laws of the Kingdom of Saudi Arabia. Please send complaints to memoriesksasupport@gmail.com with your plan reference, and we will look at them properly and fairly. Mandatory consumer rights and the jurisdiction of the competent Saudi authorities remain unaffected.", "We may update these Terms prospectively. The date at the top of this page shows the current version, and a change will never be applied backwards to a plan you have already paid for."] },
];

export const termsAr: LegalSection[] = [
  { id: "scope", title: "النطاق والموافقة", paragraphs: ["تحكم هذه الشروط استخدامك لموقع memories.tours وأي طلب ترسله إلى ميموريز. وباستخدام الموقع أو إرسال طلب، فإنك تؤكد أهليتك للتعاقد وأن المعلومات التي قدمتها صحيحة ومشروعة."] },
  { id: "what-we-sell", title: "ما نبيعه، وما لا نفعله", paragraphs: ["تبيع ميموريز خطة سفر مكتوبة. هذا هو المنتج بالكامل. نحن لسنا وكالة سفر ولا منظم رحلات ولا منصة حجز، ولا تربطنا وكالة أو انتساب أو أي ترتيب تجاري بأي شركة طيران أو فندق أو سائق أو مطعم أو مزود نشاط نذكره.", "نحن لا نحجز لك شيئًا، ولن نفعل بموجب هذه الشروط. لا نحجز مقاعد ولا نصدر تذاكر ولا نستلم عربونًا نيابة عن مزود ولا نعمل وسيطًا بينك وبين أي مزود. خطتك تخبرك بما تحجزه وأين تحجزه وكم من الوقت قبله تقريبًا، وأنت من يقوم بكل حجز بنفسه وباسمه ومباشرة مع المزود ووفق شروط ذلك المزود وسعره هو.", "ولا شيء مما ننتجه يُعد حجزًا: لا الخطة ولا النظرة العامة ولا فندق مذكور بالاسم ولا رقم تقديري. وإن أردت تثبيت شيء، فعليك الذهاب وتثبيته بنفسك."] },
  { id: "the-plan", title: "كيف تُكتب خطتك", paragraphs: ["تُكتب خطتك بواسطة نظام ذكاء اصطناعي انطلاقًا من إجاباتك ومن بحث نحتفظ به عن الوجهة ومن بحث حديث على الإنترنت، ثم يقرأها شخص من فريقنا قبل أن تصلك. ونحن نأخذ تلك المراجعة على محمل الجد، ومع ذلك تبقى وثيقة عن العالم الحقيقي كُتبت مسبقًا.", "فأوقات العمل والأسعار والإغلاقات الموسمية وقواعد الدخول ومتطلبات التأشيرات تتغير، أحيانًا خلال مدة قصيرة، وأحيانًا بين كتابتنا للخطة وسفرك أنت. تعامل مع خطتك بوصفها إرشادًا مدروسًا تتصرف على أساسه، لا ضمانًا لحقيقة. وتحقق من كل ما يهم، وخصوصًا ما ستدفع مقابله أو ما يحدد إمكانية دخولك بلدًا ما، مع المزود أو الجهة المختصة قبل الاعتماد عليه."] },
  { id: "fees", title: "رسومنا، وتكلفة السفر", paragraphs: ["رسومنا مقابل الخطة فقط. وهي 15 ريالًا عن كل ليلة من الرحلة، بالإضافة إلى 20 ريالًا عن كل وجهة بعد الأولى، وبحد أقصى ثلاث وجهات، ويعرض المخطط الرسوم أثناء تعبئتك النموذج. أما خطط الدراسة بالخارج فيسعّرها فريقنا بعد الاطلاع على الطلب.", "وكل رقم يخص السفر داخل الخطة هو تقدير يساعدك على وضع ميزانيتك. ليس عرض سعر، ولا سعرًا حجزناه، ولا سعرًا وافق أحد على تثبيته لك. أنت تدفع للمزودين مباشرة ما يطلبونه في حينه. ولا نتقاضى أي عمولة من أي مزود نذكره، وذكر أي جهة ليس توصية تنطوي على مصلحة مالية لنا."] },
  { id: "traveller", title: "مسؤولياتك", bullets: ["تقديم معلومات دقيقة في نموذج التخطيط. فالخطة المبنية على تواريخ أو عدد مسافرين أو ميزانية خاطئة ستكون خاطئة بطرق لا نستطيع رؤيتها.", "حيازة جوازات السفر والتأشيرات والتصاريح والتأمين والتطعيمات ووثائق الدخول التي تطلبها الجهات المختصة.", "التحقق بنفسك من قواعد الدخول والمتطلبات الصحية وشروط المزودين قبل الحجز أو السفر، مهما ذكرت خطتك.", "إجراء حجوزاتك وإدارتها بنفسك، وقراءة شروط كل مزود تحجز معه.", "إخبارنا عند طلب الخطة باحتياجات الوصول أو الحركة أو الغذاء أو غيرها، لتراعيها الخطة.", "عدم إساءة استخدام الموقع أو تقديم محتوى غير مشروع أو محاولة وصول غير مصرح به أو انتحال شخصية غيرك."] },
  { id: "visa", title: "التأشيرات والدراسة والقرارات الرسمية", paragraphs: ["قد تشرح الخطة مسار تأشيرة أو قائمة مستندات أو إجراءات تقديم. وهذه معلومات لا تمثيل: نحن لا نقدّم الطلبات نيابة عنك ولسنا وكيلك أمام أي جهة.", "وقرارات التأشيرة والهجرة والقبول والمنح والحدود تعود وحدها إلى الجهات الرسمية أو التعليمية. ولا نضمن نتيجة ولا مدة معالجة، ولا نتحمل مسؤولية رفض أو تأخير أو قاعدة تغيرت بعد كتابة خطتك."] },
  { id: "content", title: "محتوى الموقع والملكية الفكرية", paragraphs: ["اسم ميموريز وهويتها ونصوصها الأصلية وتصميمها ومحتوى الموقع محمية بموجب أنظمة الملكية الفكرية المعمول بها. وخطتك مرخّصة لك لرحلتك أنت: يمكنك الاحتفاظ بها وطباعتها ومشاركتها مع من يسافر معك، ولا يجوز إعادة بيعها أو نشرها أو استخدامها تجاريًا. وتبقى أسماء وصور الأطراف الثالثة ملكًا لأصحابها."] },
  { id: "liability", title: "المسؤولية", paragraphs: ["لا تستبعد هذه الشروط أي مسؤولية لا يجوز استبعادها نظامًا، وحقوقك الإلزامية كمستهلك بموجب الأنظمة السعودية غير متأثرة.", "ولأننا لا نحجز شيئًا ولا نقدم أي خدمة سفر، فإننا لسنا مسؤولين عما يفعله أي مزود أو يخفق فيه: رحلة ملغاة، أو فندق لا يعترف بحجز، أو معلم مغلق، أو سائق لم يحضر، أو حجز زائد، أو تغير سعر، أو منع دخول. فهذه بينك وبين ذلك المزود أو تلك الجهة.", "وفي الحدود التي يسمح بها النظام، تقتصر مسؤوليتنا المرتبطة بأي خطة على الرسوم التي دفعتها لنا مقابلها، ولا نتحمل الخسائر غير المباشرة أو التبعية. ولا ينطبق هذا الحد على الوفاة أو الإصابة الشخصية الناتجة عن إهمالنا، ولا على الغش، ولا على أي أمر لا يسمح النظام بتحديد المسؤولية بشأنه."] },
  { id: "law", title: "النظام والشكاوى والتحديثات", paragraphs: ["تخضع هذه الشروط لأنظمة المملكة العربية السعودية. أرسل الشكاوى إلى memoriesksasupport@gmail.com مع الرقم المرجعي لخطتك، وسننظر فيها بجدية وإنصاف. وتبقى حقوق المستهلك الإلزامية واختصاص الجهات السعودية المختصة غير متأثرة.", "وقد نحدّث هذه الشروط بأثر مستقبلي. ويوضح التاريخ أعلى الصفحة النسخة الحالية، ولن يُطبق أي تغيير بأثر رجعي على خطة سبق أن دفعت مقابلها."] },
];

export const bookingEn: LegalSection[] = [
  { id: "no-booking", title: "We do not book anything", paragraphs: ["This page is about buying a plan from us. It is not about booking travel, because we do not book travel. There is no reservation to cancel with MEMORIES, no ticket we hold on your behalf and no supplier relationship between us.", "When you book the flights, hotels, cars and experiences your plan names, you book them yourself, directly, on each supplier\u2019s terms. Their cancellation rules, their change fees and their refunds are between you and them, and they are unaffected by anything on this page."] },
  { id: "preview", title: "What you get before paying anything", paragraphs: ["Every plan is delivered before you decide whether to buy it, so you are never paying for something you have not seen. Free, you get the whole overview, including which hotel and which driver we picked and the reasoning behind each choice, the first full day of every destination, and the headings of the remaining days so you can see the shape of what you would be buying.", "On a one-night trip there is no free day, only the overview, because a single free day would be the entire plan."] },
  { id: "unlocking", title: "Paying, and what it unlocks", paragraphs: ["Paying the fee unlocks every remaining day of that plan, permanently, in both English and Arabic. The plan is delivered instantly on payment, and it stays available at your own plan link.", "You may share your plan link with the people travelling with you. Please do not publish it or pass it to people outside your trip; the licence in our Terms covers your own journey."] },
  { id: "revision", title: "Your free revision", paragraphs: ["One revision of the same trip is included. That covers a different hotel, a slower or faster pace, different restaurants, or a small shift in dates, and you can request it by replying to us with your plan reference.", "A different city, a different set of dates or a different group of travellers is a different trip, and that is a new plan at the usual fee. This is not a technicality: the research, the routing and the reasoning are rebuilt from the start."] },
  { id: "refunds", title: "Refunds", paragraphs: ["Because a plan is delivered in full the moment you pay, there is no refund for a change of mind afterwards. That is why the free preview exists, and why we recommend reading it properly before you unlock the rest.", "If something is genuinely wrong on our side, that is different and we want to hear about it: a plan for the wrong dates or the wrong city, days that never arrived, a plan you paid for and cannot open, or a factual error serious enough to undermine the plan. Email memoriesksasupport@gmail.com with your plan reference and we will look at it properly and put it right, by correcting the plan, reissuing it, or refunding it where that is the fair answer.", "Your mandatory rights under Saudi consumer law are unaffected by anything in this section."] },
  { id: "cancelling-travel", title: "Cancelling or changing your actual trip", paragraphs: ["If your trip is cancelled, postponed or disrupted after you have booked it, contact the airline, hotel or provider you booked with. They hold your reservation and your money, and only they can change or refund it. We have no access to your bookings and cannot act on them.", "We are happy to be told, and if a plan is still useful for new dates we will say so, but a disrupted trip does not create a refund of our planning fee, since the plan was researched, written and delivered."] },
  { id: "insurance", title: "Documents, health and insurance", paragraphs: ["You are responsible for passports, visas, entry permissions, insurance and health requirements, and these can change at short notice. We strongly recommend comprehensive travel insurance covering cancellation, medical care, interruption, baggage and supplier failure.", "Any guidance in your plan must be checked independently with the relevant authority or supplier before you rely on it."] },
];

export const bookingAr: LegalSection[] = [
  { id: "no-booking", title: "نحن لا نحجز شيئًا", paragraphs: ["هذه الصفحة تتعلق بشراء خطة سفر من ميموريز، وليست بحجز خدمات السفر. نحن لا نقوم بحجز الرحلات أو الفنادق أو السيارات أو التجارب نيابةً عنك، ولا نحتفظ بأي تذاكر أو حجوزات، كما لا تنشأ بين ميموريز وأي مزود خدمة علاقة تعاقدية نيابةً عنك.", "عند اختيارك تنفيذ المقترحات الواردة في خطتك، فإنك تقوم بالحجز بنفسك وبشكل مباشر مع مزود الخدمة، وتخضع تلك الحجوزات لشروط وأحكام كل مزود. لذلك، فإن سياسات الإلغاء أو التعديل أو الاسترداد وأي رسوم مرتبطة بها تكون بينك وبين مزود الخدمة مباشرة، ولا ترتبط بشرائك للخطة من ميموريز أو تتأثر بما ورد في هذه الصفحة."] },
  { id: "preview", title: "ما تحصل عليه قبل أن تدفع شيئًا", paragraphs: ["تُسلَّم كل خطة قبل أن تقرر شراءها، فلا تدفع أبدًا مقابل شيء لم تره. مجانًا تحصل على النظرة العامة كاملة، بما فيها الفندق والسائق اللذان اخترناهما وسبب كل اختيار، واليوم الأول كاملًا من كل وجهة، وعناوين بقية الأيام لترى شكل ما ستشتريه.", "وفي رحلة من ليلة واحدة لا يوجد يوم مجاني، بل النظرة العامة فقط، لأن يومًا مجانيًا واحدًا سيكون هو الخطة كاملة."] },
  { id: "unlocking", title: "الدفع وما يفتحه", paragraphs: ["دفع الرسوم يفتح كل الأيام المتبقية من تلك الخطة بشكل دائم، بالعربية والإنجليزية معًا. وتُسلَّم الخطة فور الدفع وتبقى متاحة على رابط خطتك.", "ولك أن تشارك رابط خطتك مع من يسافر معك. ونرجو عدم نشره أو إعطائه لمن هم خارج رحلتك، فالترخيص في شروطنا يغطي رحلتك أنت."] },
  { id: "revision", title: "تعديلك المجاني", paragraphs: ["يشمل السعر تعديلًا واحدًا على الرحلة نفسها. ويغطي فندقًا مختلفًا، أو إيقاعًا أهدأ أو أسرع، أو مطاعم أخرى، أو تعديلًا بسيطًا في التواريخ، ويمكنك طلبه بالرد علينا مع الرقم المرجعي لخطتك.", "أما مدينة مختلفة أو تواريخ مختلفة أو مجموعة مسافرين مختلفة فهي رحلة مختلفة، وتلك خطة جديدة بالرسوم المعتادة. وهذا ليس تفصيلًا شكليًا: فالبحث والمسار والتفكير يُبنى من جديد بالكامل."] },
  { id: "refunds", title: "الاسترداد", paragraphs: ["لأن الخطة تُسلَّم كاملة لحظة الدفع، لا يوجد استرداد لتغيير الرأي بعد ذلك. ولهذا السبب وُجدت المعاينة المجانية، ولهذا ننصح بقراءتها جيدًا قبل فتح بقية الخطة.", "أما إن كان هناك خطأ حقيقي من طرفنا فالأمر مختلف ونود أن نسمعه: خطة بتواريخ خاطئة أو مدينة خاطئة، أو أيام لم تصل، أو خطة دفعت مقابلها ولا تستطيع فتحها، أو خطأ في المعلومات جسيم بما يقوّض الخطة. راسلنا على memoriesksasupport@gmail.com مع الرقم المرجعي وسننظر في الأمر بجدية ونصلحه، إما بتصحيح الخطة أو إعادة إصدارها أو ردّ المبلغ حين يكون ذلك هو الإنصاف.", "وحقوقك الإلزامية بموجب نظام حماية المستهلك السعودي غير متأثرة بأي مما ورد في هذا القسم."] },
  { id: "cancelling-travel", title: "إلغاء رحلتك الفعلية أو تغييرها", paragraphs: ["إذا أُلغيت رحلتك أو أُجّلت أو تعطلت بعد حجزك لها، تواصل مع شركة الطيران أو الفندق أو المزود الذي حجزت معه. فهو من يملك حجزك وأموالك، وهو وحده من يستطيع تغييره أو ردّه. ونحن لا نملك أي وصول إلى حجوزاتك ولا نستطيع التصرف فيها.", "ويسعدنا أن تخبرنا، وإن كانت الخطة ما زالت صالحة لتواريخ جديدة فسنقول لك ذلك، غير أن تعطل الرحلة لا ينشئ استردادًا لرسوم التخطيط، لأن الخطة بُحثت وكُتبت وسُلّمت."] },
  { id: "insurance", title: "الوثائق والصحة والتأمين", paragraphs: ["أنت مسؤول عن جوازات السفر والتأشيرات وتصاريح الدخول والتأمين والمتطلبات الصحية، وهي قد تتغير خلال مدة قصيرة. ونوصي بشدة بتأمين سفر شامل يغطي الإلغاء والرعاية الطبية والانقطاع والأمتعة وتعثر المزود.", "ويجب التحقق من أي إرشاد في خطتك بشكل مستقل مع الجهة المختصة أو المزود قبل الاعتماد عليه."] },
];

export const cookiesEn: LegalSection[] = [
  { id: "current", title: "What the site currently uses", paragraphs: ["MEMORIES currently uses only technology needed to provide the experience, including local storage to remember your light/dark theme preference and standard hosting/security logs. We do not currently use advertising cookies or third-party behavioral profiling on the site."] },
  { id: "meaning", title: "Cookies and similar technologies", paragraphs: ["Cookies are small files placed on a browser. Similar technologies include local storage and pixels. Strictly necessary technologies support security, navigation, preferences and form operation. Optional analytics or marketing technologies measure audiences or personalize advertising and generally require a separate choice where applicable."] },
  { id: "control", title: "Your controls", paragraphs: ["You can clear browser storage or block cookies in your browser settings. Blocking essential storage may reset your theme choice or affect some site behavior. Because we do not currently deploy optional advertising or analytics cookies, the site does not display a consent banner."] },
  { id: "future", title: "If this changes", paragraphs: ["Before adding non-essential analytics, advertising pixels or similar tracking, we will update this notice and, where required, provide a clear consent control that allows you to accept or reject optional categories without losing access to the core service."] },
];

export const cookiesAr: LegalSection[] = [
  { id: "current", title: "ما يستخدمه الموقع حاليًا", paragraphs: ["يستخدم موقع ميموريز حاليًا تقنيات لازمة للتجربة فقط، ومنها التخزين المحلي لتذكر الوضع الفاتح أو الداكن وسجلات الاستضافة والأمن المعتادة. لا نستخدم حاليًا ملفات إعلانية أو تتبعًا سلوكيًا من أطراف ثالثة."] },
  { id: "meaning", title: "ملفات الارتباط والتقنيات المشابهة", paragraphs: ["ملفات الارتباط ملفات صغيرة توضع في المتصفح، وتشمل التقنيات المشابهة التخزين المحلي والبكسلات. تدعم التقنيات الضرورية الأمن والتنقل والتفضيلات والنماذج، بينما تقيس التقنيات الاختيارية الجمهور أو تخصص الإعلانات وعادة تتطلب اختيارًا منفصلًا حيث ينطبق."] },
  { id: "control", title: "خياراتك", paragraphs: ["يمكنك مسح تخزين المتصفح أو حظر ملفات الارتباط من الإعدادات. قد يؤدي حظر التخزين الأساسي إلى إعادة ضبط تفضيل المظهر أو التأثير على بعض وظائف الموقع. ولأننا لا نستخدم الآن ملفات إعلانية أو تحليلية اختيارية، فلا نعرض نافذة موافقة."] },
  { id: "future", title: "إذا تغير ذلك", paragraphs: ["قبل إضافة تحليلات غير ضرورية أو بكسلات إعلانية أو تقنيات مشابهة، سنحدث هذه السياسة ونوفر عند الحاجة خيار موافقة واضحًا يسمح بقبول أو رفض الفئات الاختيارية دون فقدان الخدمة الأساسية."] },
];
