import type { LegalSection } from "./components/legal-page";

export const legalUpdatedEn = "13 August 2026";
export const legalUpdatedAr = "13 أغسطس 2026";

export const privacyEn: LegalSection[] = [
  { id: "who-we-are", title: "Who we are", paragraphs: ["This notice explains how MEMORIES Travel (\"MEMORIES\", \"we\", \"us\") handles personal data through memories.tours, our journey-request forms, email, WhatsApp and related customer-support channels. MEMORIES is based in Riyadh, Saudi Arabia. Our privacy contact is memoriesksasupport@gmail.com."] },
  { id: "data-we-collect", title: "Information we collect", bullets: ["Identity and contact data, such as your name, email address, telephone number, country code and preferred contact channel.", "Journey information, including destination, dates, traveller type and count, budget, transport, accommodation, experiences, study-abroad needs and any notes you choose to provide.", "Information about companions that you provide. You must have permission to share their information and should avoid including passport, health or other sensitive data until we specifically request it through a secure channel.", "Technical data needed to operate and secure the website, such as IP address, browser/device information, server logs and essential local-storage preferences.", "Marketing preference and newsletter email address, only when you separately choose to subscribe."] },
  { id: "why-we-use", title: "Why we use your information", paragraphs: ["We use journey-request information to respond to you, prepare or discuss a proposal, provide customer service, prevent misuse, maintain business records and comply with legal obligations. Sending a journey request authorizes service communications about that request; it does not subscribe you to marketing.", "Where required, we rely on your consent for optional marketing. You can withdraw that consent at any time. We do not sell personal data."] },
  { id: "sharing", title: "Who we share it with", paragraphs: ["We use service providers to operate the website and communications, including Vercel for hosting and Resend for email delivery. If you proceed beyond an enquiry, relevant information may be shared with selected airlines, hotels, transport providers, activity operators, educational or visa-support partners and payment providers to obtain quotes or fulfil services. We share only what is reasonably necessary and remain responsible for our own handling of your data."], bullets: ["Government, immigration, law-enforcement or regulatory bodies when legally required.", "Professional advisers and technology/security providers bound by appropriate duties.", "A successor organization in a lawful merger, acquisition or restructuring, subject to applicable safeguards."] },
  { id: "international", title: "International transfers", paragraphs: ["Travel planning naturally involves providers in other countries. Our hosting and email providers may also process data outside Saudi Arabia. Where personal data is transferred internationally, we will use the mechanisms and safeguards required by applicable Saudi data-protection law and limit transfers to what is necessary for the stated purpose."] },
  { id: "retention", title: "How long we keep it", paragraphs: ["Unconverted journey enquiries are ordinarily kept for up to 24 months after the last meaningful contact, then deleted or anonymized unless a longer period is needed for a complaint, legal claim, fraud prevention or law. Booking, payment and tax records may be retained for the period required by applicable law. Marketing contact information is kept until you unsubscribe or ask us to delete it."] },
  { id: "rights", title: "Your choices and rights", paragraphs: ["Subject to applicable law, you may ask to be informed about our processing, access your data, obtain a copy, correct it, request deletion, withdraw consent or object to certain uses. You can unsubscribe using the link in any marketing email or by contacting us. We may verify your identity and may retain limited information where the law requires it. Send requests to memoriesksasupport@gmail.com. You may also raise a complaint with the competent Saudi data-protection authority."] },
  { id: "security", title: "Security and children", paragraphs: ["We use reasonable technical and organizational measures to protect information, but no online service is completely risk-free. Do not submit passport scans, payment-card details or medical information in free-text fields. Our service is not directed to children acting independently; a parent or legal guardian must submit and manage requests involving minors."] },
  { id: "changes", title: "Changes to this notice", paragraphs: ["We may update this notice when our services, providers or legal obligations change. The date at the top shows the latest version. Material changes will be highlighted where appropriate."] },
];

export const privacyAr: LegalSection[] = [
  { id: "who-we-are", title: "من نحن", paragraphs: ["توضح هذه السياسة كيفية تعامل ميموريز للسفر (\"ميموريز\" أو \"نحن\") مع البيانات الشخصية عبر memories.tours ونماذج طلب الرحلات والبريد الإلكتروني وواتساب وقنوات الدعم ذات الصلة. يقع مقر ميموريز في الرياض، المملكة العربية السعودية، ويمكن التواصل بشأن الخصوصية عبر memoriesksasupport@gmail.com."] },
  { id: "data-we-collect", title: "البيانات التي نجمعها", bullets: ["بيانات الهوية والتواصل مثل الاسم والبريد الإلكتروني ورقم الجوال ورمز الدولة وطريقة التواصل المفضلة.", "تفاصيل الرحلة مثل الوجهة والتواريخ ونوع وعدد المسافرين والميزانية والنقل والإقامة والتجارب واحتياجات الدراسة في الخارج والملاحظات التي تختار تقديمها.", "بيانات المرافقين التي تقدمها؛ يجب أن تكون مخولًا بمشاركتها، وتجنب إدخال جوازات السفر أو البيانات الصحية أو الحساسة حتى نطلبها عبر قناة آمنة.", "بيانات تقنية لازمة لتشغيل الموقع وحمايته مثل عنوان الإنترنت ونوع الجهاز والمتصفح وسجلات الخادم وتفضيلات العرض الأساسية.", "البريد الإلكتروني وتفضيل التسويق فقط عند الاشتراك المنفصل في القائمة البريدية."] },
  { id: "why-we-use", title: "لماذا نستخدم بياناتك", paragraphs: ["نستخدم بيانات طلب الرحلة للرد عليك وإعداد أو مناقشة عرض وخدمة العملاء ومنع إساءة الاستخدام وحفظ السجلات والامتثال للالتزامات النظامية. إرسال الطلب يسمح لنا بإرسال رسائل خدمية مرتبطة به، ولا يعني الاشتراك في التسويق.", "نعتمد على موافقتك عندما تكون الرسائل التسويقية اختيارية، ويمكنك سحبها في أي وقت. نحن لا نبيع بياناتك الشخصية."] },
  { id: "sharing", title: "مع من نشارك البيانات", paragraphs: ["نستخدم مزودي خدمات لتشغيل الموقع والاتصالات، بما في ذلك Vercel للاستضافة وResend لإرسال البريد. وإذا انتقل الطلب من الاستفسار إلى التنفيذ، فقد نشارك البيانات اللازمة مع شركات الطيران والفنادق ومقدمي النقل والأنشطة وشركاء التعليم أو التأشيرات ومزودي الدفع للحصول على عروض أو تنفيذ الخدمات."], bullets: ["الجهات الحكومية أو التنظيمية أو الأمنية عند وجود التزام نظامي.", "المستشارون ومزودو التقنية والأمن الملتزمون بواجبات مناسبة.", "الجهة الخلف في اندماج أو استحواذ أو إعادة هيكلة مشروعة مع الضمانات اللازمة."] },
  { id: "international", title: "نقل البيانات خارج المملكة", paragraphs: ["قد يتطلب التخطيط للسفر التعامل مع مزودين في دول أخرى، وقد يعالج مزودو الاستضافة والبريد البيانات خارج المملكة. سنلتزم بالمتطلبات والضمانات النظامية السعودية المطبقة، ونقصر النقل على ما يلزم للغرض المعلن."] },
  { id: "retention", title: "مدة الاحتفاظ", paragraphs: ["نحتفظ عادة بطلبات الرحلات التي لم تتحول إلى حجز لمدة تصل إلى 24 شهرًا من آخر تواصل جوهري، ثم نحذفها أو نجعلها غير معرفة، ما لم نحتج مدة أطول لشكوى أو مطالبة أو منع الاحتيال أو التزام نظامي. قد نحتفظ بسجلات الحجز والدفع والضرائب للفترة التي يفرضها النظام. وتبقى بيانات التسويق حتى إلغاء الاشتراك أو طلب الحذف."] },
  { id: "rights", title: "حقوقك وخياراتك", paragraphs: ["وفقًا للنظام المطبق، يمكنك طلب معرفة كيفية معالجة بياناتك والوصول إليها والحصول على نسخة وتصحيحها وطلب حذفها وسحب الموافقة أو الاعتراض على بعض الاستخدامات. يمكنك إلغاء الاشتراك من الرابط الموجود في أي رسالة تسويقية أو بالتواصل معنا. قد نتحقق من هويتك، وقد نحتفظ بالحد الأدنى الذي يفرضه النظام. أرسل الطلب إلى memoriesksasupport@gmail.com، ويمكنك تقديم شكوى إلى الجهة السعودية المختصة بحماية البيانات."] },
  { id: "security", title: "الأمن وبيانات القاصرين", paragraphs: ["نطبق تدابير تقنية وتنظيمية معقولة، لكن لا توجد خدمة إلكترونية خالية تمامًا من المخاطر. لا تضع صور جواز السفر أو بيانات البطاقات أو المعلومات الطبية في حقول النص الحر. يجب أن يقدم ولي الأمر أو الوصي الطلبات المتعلقة بالقاصرين ويديرها."] },
  { id: "changes", title: "تحديث السياسة", paragraphs: ["قد نحدث هذه السياسة عند تغير خدماتنا أو مزودينا أو التزاماتنا. يوضح التاريخ أعلى الصفحة أحدث نسخة، وسنبرز التغييرات الجوهرية عند الحاجة."] },
];

export const termsEn: LegalSection[] = [
  { id: "scope", title: "Scope and acceptance", paragraphs: ["These Terms govern your use of memories.tours and any request you send to MEMORIES. By using the site or submitting a request, you confirm that you can enter a binding agreement and that the information you provide is accurate and lawful."] },
  { id: "enquiry", title: "An enquiry is not a booking", paragraphs: ["The website currently collects journey enquiries. A submission, automated acknowledgment, proposed itinerary or estimate is not a confirmed reservation and does not guarantee availability, price, admission, visa approval or supplier acceptance. A booking exists only after we issue written confirmation stating the agreed services, total price, payment terms and applicable supplier conditions."] },
  { id: "our-role", title: "Our role and third-party providers", paragraphs: ["Depending on the service, MEMORIES may arrange, coordinate or facilitate travel supplied by third parties such as airlines, hotels, transport operators, activity providers, educational organizations and visa-support specialists. Their own rules may apply and will be disclosed before a binding booking. We remain responsible for the services we directly promise, but not for independent acts outside our reasonable control except where applicable law provides otherwise."] },
  { id: "accuracy", title: "Prices, information and availability", paragraphs: ["Destination content is inspirational and may change. Prices, exchange rates, schedules and availability are dynamic. Any final offer will identify included services, taxes and disclosed fees. We may correct an obvious error before confirmation. You are responsible for checking names, dates and other details before accepting a proposal."] },
  { id: "traveller", title: "Traveller responsibilities", bullets: ["Provide complete and accurate traveller information and promptly review all confirmations.", "Hold valid passports, visas, permits, insurance, vaccinations and entry documents required by the relevant authorities.", "Follow supplier rules, local laws, safety instructions and reasonable conduct standards.", "Tell us before booking about accessibility, mobility, dietary or other requirements that may affect arrangements.", "Do not misuse the website, submit unlawful content, attempt unauthorized access or impersonate another person."] },
  { id: "visa", title: "Visas, study and official decisions", paragraphs: ["MEMORIES may provide administrative guidance or application assistance. Visa, immigration, admission, scholarship and border decisions are made solely by the relevant authorities or institutions. We do not guarantee approval or processing time and are not responsible for refusal caused by an authority, missing/inaccurate information or circumstances outside our control."] },
  { id: "content", title: "Website content and intellectual property", paragraphs: ["The MEMORIES name, branding, original copy, design and site content are protected by applicable intellectual-property law. You may use the site for personal travel enquiries but may not copy, resell, scrape or commercially exploit it without written permission. Third-party names and images remain the property of their owners."] },
  { id: "liability", title: "Liability and force majeure", paragraphs: ["Nothing in these Terms excludes liability that cannot legally be excluded. To the extent permitted by law, we are not liable for indirect or consequential loss or for disruption caused by events beyond reasonable control, including weather, natural disasters, strikes, conflict, epidemics, government action, border restrictions, supplier insolvency or transport interruption. We will make reasonable efforts to assist where our confirmed service requires it."] },
  { id: "law", title: "Law, complaints and changes", paragraphs: ["These Terms are governed by the laws of the Kingdom of Saudi Arabia. Please send complaints to memoriesksasupport@gmail.com with your request or booking reference. We will attempt to resolve them fairly; mandatory consumer rights and competent authorities remain unaffected. We may update these Terms prospectively and will not silently change confirmed booking terms."] },
];

export const termsAr: LegalSection[] = [
  { id: "scope", title: "النطاق والموافقة", paragraphs: ["تحكم هذه الشروط استخدام memories.tours وأي طلب ترسله إلى ميموريز. باستخدام الموقع أو إرسال الطلب، فإنك تؤكد أهليتك للتعاقد وأن المعلومات المقدمة صحيحة ومشروعة."] },
  { id: "enquiry", title: "الطلب ليس حجزًا", paragraphs: ["يجمع الموقع حاليًا طلبات تخطيط الرحلات. لا يُعد إرسال النموذج أو الرد الآلي أو البرنامج المقترح أو التقدير حجزًا مؤكدًا، ولا يضمن التوفر أو السعر أو القبول أو التأشيرة. لا ينشأ الحجز إلا بعد تأكيد كتابي منا يحدد الخدمات والسعر الإجمالي والدفع وشروط المزودين."] },
  { id: "our-role", title: "دورنا ومزودو الخدمات", paragraphs: ["قد ترتب ميموريز أو تنسق أو تسهل خدمات يقدمها طرف ثالث مثل شركات الطيران والفنادق والنقل والأنشطة والجهات التعليمية والمتخصصين في دعم التأشيرات. قد تسري شروطهم الخاصة وسنعرضها قبل الحجز الملزم. نتحمل مسؤولية ما نعد به مباشرة، مع مراعاة حدود النظام والأحداث الخارجة عن سيطرتنا."] },
  { id: "accuracy", title: "الأسعار والمعلومات والتوفر", paragraphs: ["محتوى الوجهات للإلهام وقد يتغير. الأسعار وأسعار الصرف والمواعيد والتوفر متغيرة. سيبين العرض النهائي الخدمات والضرائب والرسوم المعلنة. يجوز تصحيح الخطأ الواضح قبل التأكيد، وعليك مراجعة الأسماء والتواريخ والتفاصيل قبل القبول."] },
  { id: "traveller", title: "مسؤوليات المسافر", bullets: ["تقديم معلومات كاملة وصحيحة ومراجعة جميع التأكيدات فورًا.", "حيازة جوازات السفر والتأشيرات والتصاريح والتأمين والتطعيمات ووثائق الدخول المطلوبة.", "اتباع شروط المزودين والأنظمة المحلية وتعليمات السلامة والسلوك المناسب.", "إبلاغنا قبل الحجز عن احتياجات الوصول أو الحركة أو الغذاء أو أي متطلبات مؤثرة.", "عدم إساءة استخدام الموقع أو تقديم محتوى غير مشروع أو محاولة الوصول غير المصرح به."] },
  { id: "visa", title: "التأشيرات والدراسة والقرارات الرسمية", paragraphs: ["قد تقدم ميموريز إرشادًا إداريًا أو مساعدة في الطلب. قرارات التأشيرة والهجرة والقبول والمنح والحدود تخص الجهات الرسمية أو التعليمية وحدها. لا نضمن الموافقة أو مدة المعالجة ولا نتحمل رفضًا سببه نقص أو خطأ البيانات أو ظرف خارج السيطرة."] },
  { id: "content", title: "محتوى الموقع والملكية الفكرية", paragraphs: ["اسم ميموريز وهويتها ومحتواها وتصميمها الأصلي محمي. يمكنك استخدام الموقع للاستفسارات الشخصية، ولا يجوز نسخه أو إعادة بيعه أو جمعه آليًا أو استغلاله تجاريًا دون إذن مكتوب. تبقى حقوق الأطراف الثالثة لأصحابها."] },
  { id: "liability", title: "المسؤولية والقوة القاهرة", paragraphs: ["لا تستبعد هذه الشروط أي مسؤولية لا يجوز استبعادها نظامًا. وفي الحدود المسموح بها، لا نتحمل الخسائر غير المباشرة أو التعطل الناتج عن أحداث خارجة عن السيطرة مثل الطقس والكوارث والإضرابات والنزاعات والأوبئة والقرارات الحكومية وقيود الحدود وإفلاس المزود أو تعطل النقل. سنبذل جهدًا معقولًا للمساعدة متى تطلبت خدمتنا المؤكدة ذلك."] },
  { id: "law", title: "النظام والشكاوى والتحديثات", paragraphs: ["تخضع هذه الشروط لأنظمة المملكة العربية السعودية. أرسل الشكاوى إلى memoriesksasupport@gmail.com مع رقم الطلب أو الحجز. سنسعى إلى حلها بعدل دون المساس بحقوق المستهلك الإلزامية أو اختصاص الجهات الرسمية. تسري التحديثات مستقبلًا ولن نغير شروط حجز مؤكد دون بيان."] },
];

export const bookingEn: LegalSection[] = [
  { id: "before", title: "Before a booking is confirmed", paragraphs: ["A journey request starts a conversation. Before payment or confirmation, we will provide the service description, traveller details, dates, included and excluded items, total price including disclosed taxes/fees, payment schedule, delivery method and the relevant cancellation/change rules. Supplier terms may vary by flight, hotel, transport or experience."] },
  { id: "confirmation", title: "Confirmation and payment", paragraphs: ["Do not make non-refundable commitments until you receive our written booking confirmation. A quote may expire and availability can change before payment. A booking is confirmed only when the stated payment is received and we send confirmation. Never send card details through the website’s free-text fields, ordinary email or WhatsApp; use only the secure payment method we identify."] },
  { id: "changes", title: "Changes and cancellations by you", paragraphs: ["Change and cancellation rights depend on the confirmed supplier rules and the stage of fulfilment. Airline tickets, accommodation, transport, dining and date-specific services may be non-refundable or subject to fees. Before you accept a booking, we will state any MEMORIES administration fee and known supplier penalty. Ask us in writing and quote your reference; we will confirm the available options and cost before acting."] },
  { id: "refunds", title: "Refunds", paragraphs: ["Where a refund is due, it will ordinarily return to the original payment method after the relevant supplier releases the funds. Supplier and bank processing times may apply. Refundable amounts exclude valid supplier penalties, used services and disclosed non-refundable fees. Mandatory rights under Saudi law remain unaffected, including any rights that apply to delayed performance; statutory exceptions may apply to accommodation, transport and catering services."] },
  { id: "supplier", title: "Changes by us or a supplier", paragraphs: ["Schedules, properties and services may change. If a material confirmed element becomes unavailable, we will notify you as soon as reasonably possible and, depending on the circumstances and applicable terms, propose an alternative, price adjustment, credit or refund. Minor operational changes that do not materially reduce the journey may not create a cancellation right."] },
  { id: "documents", title: "Documents, health and insurance", paragraphs: ["Travellers are responsible for passports, visas, entry permissions, insurance and health requirements. Requirements can change at short notice. We strongly recommend comprehensive travel insurance covering cancellation, medical care, interruption, baggage and supplier failure. Any guidance we provide must be independently checked with the relevant authority."] },
  { id: "complaints", title: "During travel and complaints", paragraphs: ["Report a problem promptly to the service provider and MEMORIES so there is a reasonable opportunity to help. Keep receipts, messages and supporting evidence. After travel, email any unresolved complaint with the booking reference and relevant documents. We will acknowledge and investigate it in accordance with applicable law and the confirmed booking terms."] },
];

export const bookingAr: LegalSection[] = [
  { id: "before", title: "قبل تأكيد الحجز", paragraphs: ["يفتح طلب الرحلة باب التواصل. قبل الدفع أو التأكيد سنقدم وصف الخدمة وبيانات المسافرين والتواريخ والمشمول وغير المشمول والسعر الإجمالي بما فيه الرسوم والضرائب المعلنة وجدول الدفع وطريقة التنفيذ وقواعد التغيير والإلغاء ذات الصلة. تختلف شروط كل شركة طيران أو فندق أو ناقل أو تجربة."] },
  { id: "confirmation", title: "التأكيد والدفع", paragraphs: ["لا ترتب التزامات غير قابلة للاسترداد قبل استلام تأكيدنا الكتابي. قد ينتهي العرض ويتغير التوفر قبل الدفع. يتأكد الحجز بعد استلام الدفعة المحددة وإصدار التأكيد. لا ترسل بيانات البطاقة في حقول الموقع أو البريد العادي أو واتساب، واستخدم فقط وسيلة الدفع الآمنة التي نحددها."] },
  { id: "changes", title: "التغيير والإلغاء من قبلك", paragraphs: ["تعتمد حقوق التغيير والإلغاء على شروط المزود المؤكدة ومرحلة التنفيذ. قد تكون تذاكر الطيران والإقامة والنقل والمطاعم والخدمات المرتبطة بتاريخ محدد غير قابلة للاسترداد أو عليها رسوم. سنوضح قبل القبول رسوم ميموريز الإدارية وأي غرامة مزود معلومة. أرسل طلبك كتابيًا مع الرقم المرجعي وسنوضح الخيارات والتكلفة قبل التنفيذ."] },
  { id: "refunds", title: "المبالغ المستردة", paragraphs: ["عند استحقاق الاسترداد، يعاد المبلغ عادة إلى وسيلة الدفع الأصلية بعد تحريره من المزود، وقد تستغرق معالجة المزود والبنك وقتًا. يُخصم ما يصح من غرامات وخدمات مستخدمة ورسوم معلنة غير قابلة للاسترداد. لا تتأثر الحقوق النظامية الإلزامية، مع مراعاة الاستثناءات التي قد تنطبق على الإيواء والنقل والإطعام."] },
  { id: "supplier", title: "التغيير من جانبنا أو المزود", paragraphs: ["قد تتغير المواعيد أو المنشآت أو الخدمات. إذا تعذر عنصر جوهري مؤكد فسنبلغك بأقرب وقت معقول، ونقترح بحسب الظروف والشروط بديلًا أو تعديل سعر أو رصيدًا أو استردادًا. لا تمنح التغييرات التشغيلية البسيطة التي لا تقلل جوهر الرحلة حقًا تلقائيًا في الإلغاء."] },
  { id: "documents", title: "الوثائق والصحة والتأمين", paragraphs: ["يتحمل المسافر مسؤولية جواز السفر والتأشيرة وتصريح الدخول والتأمين والمتطلبات الصحية التي قد تتغير سريعًا. نوصي بتأمين سفر شامل للإلغاء والعلاج والانقطاع والأمتعة وتعثر المزود. يجب التحقق من أي إرشاد نقدمه لدى الجهة المختصة."] },
  { id: "complaints", title: "أثناء السفر والشكاوى", paragraphs: ["أبلغ المزود وميموريز بالمشكلة فورًا لإتاحة فرصة معقولة للمساعدة، واحتفظ بالإيصالات والرسائل والأدلة. بعد الرحلة، أرسل أي شكوى غير محلولة مع رقم الحجز والمستندات، وسنؤكد استلامها ونحقق فيها وفق النظام وشروط الحجز المؤكدة."] },
];

export const cookiesEn: LegalSection[] = [
  { id: "current", title: "What the site currently uses", paragraphs: ["MEMORIES currently uses only technology needed to provide the experience, including local storage to remember your light/dark theme preference and standard hosting/security logs. We do not currently use advertising cookies or third-party behavioral profiling on the site."] },
  { id: "meaning", title: "Cookies and similar technologies", paragraphs: ["Cookies are small files placed on a browser. Similar technologies include local storage and pixels. Strictly necessary technologies support security, navigation, preferences and form operation. Optional analytics or marketing technologies measure audiences or personalize advertising and generally require a separate choice where applicable."] },
  { id: "control", title: "Your controls", paragraphs: ["You can clear browser storage or block cookies in your browser settings. Blocking essential storage may reset your theme choice or affect some site behavior. Because we do not currently deploy optional advertising or analytics cookies, the site does not display a consent banner."] },
  { id: "future", title: "If this changes", paragraphs: ["Before adding non-essential analytics, advertising pixels or similar tracking, we will update this notice and, where required, provide a clear consent control that allows you to accept or reject optional categories without losing access to the core service."] },
];

export const cookiesAr: LegalSection[] = [
  { id: "current", title: "ما يستخدمه الموقع حاليًا", paragraphs: ["يستخدم موقع ميموريز حاليًا تقنيات لازمة للتجربة فقط، ومنها التخزين المحلي لتذكر الوضع الفاتح أو الداكن وسجلات الاستضافة والأمن المعتادة. لا نستخدم حاليًا ملفات إعلانية أو تتبعًا سلوكيًا من أطراف ثالثة."] },
  { id: "meaning", title: "ملفات الارتباط والتقنيات المشابهة", paragraphs: ["ملفات الارتباط ملفات صغيرة توضع في المتصفح، وتشمل التقنيات المشابهة التخزين المحلي والبكسلات. تدعم التقنيات الضرورية الأمن والتنقل والتفضيلات والنماذج، بينما تقيس التقنيات الاختيارية الجمهور أو تخصص الإعلانات وعادة تتطلب اختيارًا منفصلًا حيث ينطبق."] },
  { id: "control", title: "خياراتك", paragraphs: ["يمكنك مسح تخزين المتصفح أو حظر ملفات الارتباط من الإعدادات. قد يؤدي حظر التخزين الأساسي إلى إعادة ضبط تفضيل المظهر أو التأثير على بعض وظائف الموقع. ولأننا لا نستخدم الآن ملفات إعلانية أو تحليلية اختيارية، فلا نعرض نافذة موافقة."] },
  { id: "future", title: "إذا تغير ذلك", paragraphs: ["قبل إضافة تحليلات غير ضرورية أو بكسلات إعلانية أو تقنيات مشابهة، سنحدث هذه السياسة ونوفر عند الحاجة خيار موافقة واضحًا يسمح بقبول أو رفض الفئات الاختيارية دون فقدان الخدمة الأساسية."] },
];
